//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class BaseChatViewModel;
@protocol MessageNodeViewDelegate;

@interface BaseChatCellView : UIView
{
    id <MessageNodeViewDelegate> m_delegate;
    BaseChatViewModel *m_viewModel;
    struct CGSize m_layoutSize;
    _Bool m_isLayouting;
}

@property(nonatomic) _Bool isLayouting; // @synthesize isLayouting=m_isLayouting;
@property(readonly, nonatomic) BaseChatViewModel *viewModel; // @synthesize viewModel=m_viewModel;
@property(nonatomic) __weak id <MessageNodeViewDelegate> delegate; // @synthesize delegate=m_delegate;
- (void).cxx_destruct;
- (void)onDisappear;
- (void)onAppear;
- (void)layoutFinished;
- (void)layoutInternal;
- (void)layoutSubviews;
- (void)resetLayoutCache;
- (_Bool)shouldLayoutIfNeeded;
- (_Bool)canBeReused;
- (void)prepareForReuse;
- (void)setViewModel:(id)arg1;
- (id)initWithViewModel:(id)arg1;

@end

