//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WXPBGeneratedMessage.h"

@class NSString;

@interface BizEnterpriseAttr : WXPBGeneratedMessage
{
}

+ (void)initialize;

// Remaining properties
@property(retain, nonatomic) NSString *brandUserName; // @dynamic brandUserName;
@property(nonatomic) unsigned int qyUin; // @dynamic qyUin;
@property(nonatomic) unsigned int userFlag; // @dynamic userFlag;
@property(nonatomic) unsigned int userUin; // @dynamic userUin;
@property(nonatomic) unsigned int wwMaxExposeTimes; // @dynamic wwMaxExposeTimes;

@end

