//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMBaseSessionInfo.h"

#import "WCDBCoding-Protocol.h"

@class CBottle, CBottleContact, NSMutableArray, NSString;

@interface BottleSessionInfo : MMBaseSessionInfo <WCDBCoding>
{
    NSMutableArray *arrLocalID;
    long long m___rowID;
}

+ (id)sessionInfoWithBottle:(id)arg1 isRealBottle:(_Bool)arg2 localIdList:(id)arg3;
+ (const basic_string_a490aa4c *)getWCDBPrimaryColumnName;
+ (const struct WCDBIndexHelper *)getWCDBIndexArray;
+ (unsigned long long)getWCDBIndexArrayCount;
+ (const map_490096f0 *)getFileValueTagIndexMap;
+ (id)getFileValueTypeTable;
+ (const map_490096f0 *)getPackedValueTagIndexMap;
+ (id)getPackedValueTypeTable;
+ (const map_64c9abee *)getValueNameIndexMap;
+ (id)getValueTable;
+ (id)dummyObject;
@property(nonatomic) long long __rowID; // @synthesize __rowID=m___rowID;
@property(retain, nonatomic) NSMutableArray *arrLocalID; // @synthesize arrLocalID;
- (void).cxx_destruct;
- (id)genLastMessage;
@property(retain, nonatomic) CBottleContact *bottleContact;
- (id)genBottleContact;
@property(retain, nonatomic) CBottle *bottle;
- (id)genBottle;
@property(nonatomic) _Bool isRealBottle;
@property(nonatomic) unsigned int uiBottleLocalID;
- (id)init;
- (const map_490096f0 *)getValueTagIndexMap;
- (id)getValueTypeTable;
- (const WCDBCondition_c6db074e *)db_sessionFlag;
- (const WCDBCondition_c6db074e *)db_draftMsgTime;
- (const WCDBCondition_22fabacd *)db_draftMsg;
- (const WCDBCondition_c6db074e *)db_lastMsgUpdateTime;
- (const WCDBCondition_c6db074e *)db_unreadCount;
- (const WCDBCondition_22fabacd *)db_sessionId;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(retain, nonatomic) NSString *sessionId;
@property(readonly) Class superclass;

@end

