//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSString;

@interface CAppBrandInfo : NSObject
{
    _Bool _hasAppInfo;
    unsigned int versionState;
    unsigned int maxPkgSize;
    unsigned int maxUploadConcurrent;
    unsigned int maxDownloadConcurrent;
    unsigned int maxLocalstorageSize;
    unsigned int maxBackgroundLifespan;
    unsigned int maxRequestConcurrent;
    unsigned int maxWebviewDepth;
    unsigned int runningFlag;
    unsigned int _appRole;
    unsigned int _wechatPluginApp;
    unsigned int _profileCommentForbid;
    unsigned int _expiresAtList;
    unsigned int _maxFileStorageSize;
    unsigned int _backgroundNetworkInterruptedTimeout;
    NSString *appid;
    unsigned long long appVersion;
    NSString *versionPkgMD5;
    NSString *_regitserBody;
    NSString *_runningOpenForbbidenUrl;
    NSArray *_templateList;
    NSArray *_versionList;
    NSArray *_requestDomain;
    NSArray *_wsRequestDomain;
    NSArray *_uploadDomain;
    NSArray *_downloadDomain;
    NSArray *_categories;
    NSArray *_bizEntryInfo;
}

@property(retain, nonatomic) NSArray *bizEntryInfo; // @synthesize bizEntryInfo=_bizEntryInfo;
@property(retain, nonatomic) NSArray *categories; // @synthesize categories=_categories;
@property(nonatomic) unsigned int backgroundNetworkInterruptedTimeout; // @synthesize backgroundNetworkInterruptedTimeout=_backgroundNetworkInterruptedTimeout;
@property(nonatomic) unsigned int maxFileStorageSize; // @synthesize maxFileStorageSize=_maxFileStorageSize;
@property(nonatomic) unsigned int expiresAtList; // @synthesize expiresAtList=_expiresAtList;
@property(retain, nonatomic) NSArray *downloadDomain; // @synthesize downloadDomain=_downloadDomain;
@property(retain, nonatomic) NSArray *uploadDomain; // @synthesize uploadDomain=_uploadDomain;
@property(retain, nonatomic) NSArray *wsRequestDomain; // @synthesize wsRequestDomain=_wsRequestDomain;
@property(retain, nonatomic) NSArray *requestDomain; // @synthesize requestDomain=_requestDomain;
@property(retain, nonatomic) NSArray *versionList; // @synthesize versionList=_versionList;
@property(nonatomic) unsigned int profileCommentForbid; // @synthesize profileCommentForbid=_profileCommentForbid;
@property(nonatomic) unsigned int wechatPluginApp; // @synthesize wechatPluginApp=_wechatPluginApp;
@property(retain, nonatomic) NSArray *templateList; // @synthesize templateList=_templateList;
@property(nonatomic) unsigned int appRole; // @synthesize appRole=_appRole;
@property(copy, nonatomic) NSString *runningOpenForbbidenUrl; // @synthesize runningOpenForbbidenUrl=_runningOpenForbbidenUrl;
@property(nonatomic) _Bool hasAppInfo; // @synthesize hasAppInfo=_hasAppInfo;
@property(copy, nonatomic) NSString *regitserBody; // @synthesize regitserBody=_regitserBody;
@property(nonatomic) unsigned int runningFlag; // @synthesize runningFlag;
@property(nonatomic) unsigned int maxWebviewDepth; // @synthesize maxWebviewDepth;
@property(nonatomic) unsigned int maxRequestConcurrent; // @synthesize maxRequestConcurrent;
@property(nonatomic) unsigned int maxBackgroundLifespan; // @synthesize maxBackgroundLifespan;
@property(nonatomic) unsigned int maxLocalstorageSize; // @synthesize maxLocalstorageSize;
@property(nonatomic) unsigned int maxDownloadConcurrent; // @synthesize maxDownloadConcurrent;
@property(nonatomic) unsigned int maxUploadConcurrent; // @synthesize maxUploadConcurrent;
@property(nonatomic) unsigned int maxPkgSize; // @synthesize maxPkgSize;
@property(copy, nonatomic) NSString *versionPkgMD5; // @synthesize versionPkgMD5;
@property(nonatomic) unsigned long long appVersion; // @synthesize appVersion;
@property(nonatomic) unsigned int versionState; // @synthesize versionState;
@property(copy, nonatomic) NSString *appid; // @synthesize appid;
- (void).cxx_destruct;

@end

