//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface CdnSnsTaskInfo : NSObject
{
    int m_nRetCode;
    unsigned long long m_ui64StartTime;
    unsigned int m_uiFileType;
    unsigned int m_uiFileSize;
    NSString *m_nsCdnStatInfo;
}

@property(retain, nonatomic) NSString *m_nsCdnStatInfo; // @synthesize m_nsCdnStatInfo;
@property(nonatomic) unsigned int m_uiFileSize; // @synthesize m_uiFileSize;
@property(nonatomic) unsigned int m_uiFileType; // @synthesize m_uiFileType;
@property(nonatomic) unsigned long long m_ui64StartTime; // @synthesize m_ui64StartTime;
@property(nonatomic) int m_nRetCode; // @synthesize m_nRetCode;
- (void).cxx_destruct;
- (id)GetStatInfo;
- (id)init;

@end

