//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCoding-Protocol.h"

@class NSString;

@interface ContactTagItem : NSObject <NSCoding>
{
    unsigned int m_uiID;
    NSString *m_nsName;
}

@property(retain, nonatomic) NSString *m_nsName; // @synthesize m_nsName;
@property(nonatomic) unsigned int m_uiID; // @synthesize m_uiID;
- (void).cxx_destruct;
- (id)init;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;

@end

