//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "PluginContactInfoAssist.h"

@interface CQQContactInfoAssist : PluginContactInfoAssist
{
}

- (void)setQQOfflineMsgOpen:(_Bool)arg1 configType:(unsigned int)arg2 status:(unsigned int)arg3;
- (void)reloadInstalledTableViewData;
- (id)getPluginIntro;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)installPlugin;

@end

