//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "WCDBCoding-Protocol.h"

@class NSString;

@interface DBEmoticonDownload : NSObject <WCDBCoding>
{
    unsigned int offset;
    unsigned int status;
    unsigned int createTime;
    unsigned int type;
    unsigned int imageStatus;
    unsigned int catalogId;
    unsigned int messageFlag;
    unsigned int messageFrom;
    unsigned int ConIntRes3;
    NSString *userName;
    NSString *msgServerId;
    NSString *message;
    NSString *catalog;
    NSString *draft;
    NSString *messageSource;
    NSString *ConStrRes2;
    NSString *ConStrRes3;
    long long m___rowID;
}

+ (const basic_string_a490aa4c *)getWCDBPrimaryColumnName;
+ (const struct WCDBIndexHelper *)getWCDBIndexArray;
+ (unsigned long long)getWCDBIndexArrayCount;
+ (const map_490096f0 *)getFileValueTagIndexMap;
+ (id)getFileValueTypeTable;
+ (const map_490096f0 *)getPackedValueTagIndexMap;
+ (id)getPackedValueTypeTable;
+ (const map_64c9abee *)getValueNameIndexMap;
+ (id)getValueTable;
+ (id)dummyObject;
@property(nonatomic) long long __rowID; // @synthesize __rowID=m___rowID;
@property(retain, nonatomic) NSString *ConStrRes3; // @synthesize ConStrRes3;
@property(retain, nonatomic) NSString *ConStrRes2; // @synthesize ConStrRes2;
@property(retain, nonatomic) NSString *messageSource; // @synthesize messageSource;
@property(nonatomic) unsigned int ConIntRes3; // @synthesize ConIntRes3;
@property(nonatomic) unsigned int messageFrom; // @synthesize messageFrom;
@property(nonatomic) unsigned int messageFlag; // @synthesize messageFlag;
@property(retain, nonatomic) NSString *draft; // @synthesize draft;
@property(nonatomic) unsigned int catalogId; // @synthesize catalogId;
@property(retain, nonatomic) NSString *catalog; // @synthesize catalog;
@property(nonatomic) unsigned int imageStatus; // @synthesize imageStatus;
@property(retain, nonatomic) NSString *message; // @synthesize message;
@property(nonatomic) unsigned int type; // @synthesize type;
@property(nonatomic) unsigned int createTime; // @synthesize createTime;
@property(nonatomic) unsigned int status; // @synthesize status;
@property(nonatomic) unsigned int offset; // @synthesize offset;
@property(retain, nonatomic) NSString *msgServerId; // @synthesize msgServerId;
@property(retain, nonatomic) NSString *userName; // @synthesize userName;
- (void).cxx_destruct;
- (const map_490096f0 *)getValueTagIndexMap;
- (id)getValueTypeTable;
- (const WCDBCondition_22fabacd *)db_ConStrRes3;
- (const WCDBCondition_22fabacd *)db_ConStrRes2;
- (const WCDBCondition_22fabacd *)db_messageSource;
- (const WCDBCondition_c6db074e *)db_ConIntRes3;
- (const WCDBCondition_c6db074e *)db_messageFrom;
- (const WCDBCondition_c6db074e *)db_messageFlag;
- (const WCDBCondition_22fabacd *)db_draft;
- (const WCDBCondition_c6db074e *)db_catalogId;
- (const WCDBCondition_22fabacd *)db_catalog;
- (const WCDBCondition_c6db074e *)db_imageStatus;
- (const WCDBCondition_22fabacd *)db_message;
- (const WCDBCondition_c6db074e *)db_type;
- (const WCDBCondition_c6db074e *)db_createTime;
- (const WCDBCondition_c6db074e *)db_status;
- (const WCDBCondition_c6db074e *)db_offset;
- (const WCDBCondition_22fabacd *)db_msgServerId;
- (const WCDBCondition_22fabacd *)db_userName;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

