//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMObject.h"

@class NSString;

@interface DeviceRankRecordItem : MMObject
{
    unsigned int _uiRankScore;
    NSString *_nsTitle;
}

@property(nonatomic) unsigned int uiRankScore; // @synthesize uiRankScore=_uiRankScore;
@property(retain, nonatomic) NSString *nsTitle; // @synthesize nsTitle=_nsTitle;
- (void).cxx_destruct;

@end

