//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "ICdnComMgrExt-Protocol.h"

@class CdnTaskInfo, NSMutableArray, NSMutableDictionary, NSString;

@interface DownloadVideoCDNMgr : NSObject <ICdnComMgrExt>
{
    NSMutableArray *_arrDownloadTask;
    NSMutableArray *_arrPreloadTask;
    CdnTaskInfo *_curTaskInfo;
    NSMutableDictionary *m_dicDownloadVideoCache;
    NSMutableDictionary *m_dicPreloadVideoRecord;
    _Bool _bEnablePreload;
    unsigned int _uiLastCleanPreloadTmpFileTime;
}

- (void).cxx_destruct;
- (void)OnCdnVideoPreloadCompleted:(id)arg1;
- (void)OnCdnDownload:(id)arg1;
- (void)OnCdnDownloadProgress:(id)arg1;
- (void)OnSetCdnDnsInfo;
- (void)OnCdnVideoDownloadToEnd:(id)arg1;
- (void)OnCdnVideoMoovReady:(id)arg1;
- (void)OnCdnDownloadPartialData:(id)arg1;
- (void)updateVideoDownloadModeWithClientId:(id)arg1 downloadMode:(unsigned long long)arg2;
- (_Bool)IsVideoMoovHasDownloadedByMessageWrap:(id)arg1;
- (_Bool)StopVideoStreamingDownload:(id)arg1 Result:(struct C2CDownloadResult *)arg2;
- (_Bool)StartVideoStreamingDownload:(id)arg1 PlayMode:(_Bool)arg2;
- (_Bool)RequestVideoDataByClientMediaID:(id)arg1 offset:(unsigned int)arg2 length:(unsigned int)arg3 durationSec:(unsigned int)arg4;
- (_Bool)IsVideoDataAvailableByClientMediaId:(id)arg1 offset:(unsigned int)arg2 length:(unsigned int)arg3;
- (void)ResumePreload;
- (void)PausePreload;
- (void)Stop;
- (void)StopDownloadByChatName:(id)arg1;
- (void)StopDownload:(id)arg1 Result:(struct C2CDownloadResult *)arg2;
- (void)StopCurDownload;
- (void)StopCurDownload:(struct C2CDownloadResult *)arg1;
- (_Bool)canUseVideoStreamFullDownloadLogic:(id)arg1;
- (_Bool)shouldUseOldVideoDownloadLogic:(id)arg1;
- (_Bool)canUseStreamStopLogic:(id)arg1;
- (unsigned long long)GetVideoMessageDownloadingMode:(id)arg1;
- (void)StartPreloadVideo:(id)arg1;
- (unsigned long long)StartDownloadVideo:(id)arg1 AutoDownload:(_Bool)arg2 Priority:(_Bool)arg3 DownloadMode:(unsigned long long)arg4;
- (_Bool)StartDownloadVideo:(id)arg1 AutoDownload:(_Bool)arg2;
- (_Bool)IsMsgInDownloadQueue:(id)arg1;
- (void)updateFileAndCache:(id)arg1;
- (_Bool)isFirstDownloadTask:(id)arg1;
- (_Bool)checkDownloadState:(id)arg1;
- (void)CheckQueue;
- (void)localCacheDownloadSuccess;
- (void)deleteCacheForChatName:(id)arg1;
- (_Bool)CheckForLocalCache:(id)arg1;
- (void)DelTask:(id)arg1 inQueue:(id)arg2;
- (void)DelTaskInPreloadQueue:(id)arg1;
- (void)DelTaskInDownloadQueue:(id)arg1;
- (void)videoKVReportWithResult:(struct C2CDownloadResult *)arg1;
- (void)DownloadFail:(int)arg1 oDownloadInfo:(id)arg2;
- (void)DownloadOk;
- (void)updateVideoThumbImage;
- (void)ReloadPreloadRecord;
- (void)CleanAllPreloadTempFile:(unsigned long long *)arg1 Records:(id)arg2;
- (void)CleanAllPreloadTempFile:(unsigned long long *)arg1 subQueue:(id)arg2;
- (void)CleanOutOfDatePreloadTempFile;
- (void)RemovePreloadTempFile:(id)arg1;
- (void)RemovePreloadRecordByLRU;
- (void)RemovePreloadRecord:(id)arg1 shouldRemoveFile:(_Bool)arg2;
- (void)AddPreloadRecord:(id)arg1;
- (void)SavePreloadRecord;
- (void)LoadPreloadRecord;
- (id)GetPreloadVideoRecordPath;
- (void)RemoveCacheByLRU;
- (void)SaveCacheData;
- (void)LoadCacheData;
- (id)GetVideoCachePath;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

