//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "EditImageInitialViewDelegate-Protocol.h"
#import "ForwardMessageLogicDelegate-Protocol.h"
#import "IMsgRevokeExt-Protocol.h"
#import "WCActionSheetDelegate-Protocol.h"

@class CMessageWrap, EditImageAttr, EditImageIntialView, FavoritesItem, ForwardMessageLogicController, MMLoadingView, NSString, UIImage, UIViewController, WCActionSheet;
@protocol EditImageForwardAndEditLogicDelegate;

@interface EditImageForwardAndEditLogicController : NSObject <EditImageInitialViewDelegate, ForwardMessageLogicDelegate, WCActionSheetDelegate, IMsgRevokeExt>
{
    EditImageIntialView *_editImageInitialView;
    MMLoadingView *_loadingView;
    EditImageAttr *_editImageAttr;
    ForwardMessageLogicController *_forwardMessageLogicController;
    WCActionSheet *_actionsheet;
    int _editImageEntrance;
    int _editImageScene;
    id <EditImageForwardAndEditLogicDelegate> _delegate;
    CMessageWrap *_originalMessageWrap;
    UIImage *_originalImage;
    UIViewController *_currentViewController;
    FavoritesItem *_favItem;
    UIViewController *_forwardBasedViewController;
}

@property(nonatomic) int editImageScene; // @synthesize editImageScene=_editImageScene;
@property(nonatomic) int editImageEntrance; // @synthesize editImageEntrance=_editImageEntrance;
@property(nonatomic) __weak UIViewController *forwardBasedViewController; // @synthesize forwardBasedViewController=_forwardBasedViewController;
@property(retain, nonatomic) FavoritesItem *favItem; // @synthesize favItem=_favItem;
@property(nonatomic) __weak UIViewController *currentViewController; // @synthesize currentViewController=_currentViewController;
@property(retain, nonatomic) UIImage *originalImage; // @synthesize originalImage=_originalImage;
@property(retain, nonatomic) CMessageWrap *originalMessageWrap; // @synthesize originalMessageWrap=_originalMessageWrap;
@property(nonatomic) __weak id <EditImageForwardAndEditLogicDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)OnMsgRevoked:(id)arg1 n64MsgId:(long long)arg2 SysMsg:(id)arg3;
- (void)actionSheet:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)OnForwardMessageCancel:(id)arg1;
- (void)OnForwardMessageSend:(id)arg1;
- (id)getCurrentViewController;
- (void)processEditImage:(CDUnknownBlockType)arg1;
- (void)OnClickEditImageDoneBarButton;
- (void)OnClickEditImageBackBarButton;
- (void)getOriginalImage:(CDUnknownBlockType)arg1;
- (void)getDisplayImage:(CDUnknownBlockType)arg1;
- (void)forwardMessage:(id)arg1;
- (void)editImageActionSheetClickedButtonWithTitle:(id)arg1;
- (void)startEditImage;
- (void)reloadViews;
- (void)startLogic;
- (void)checkValidity;
- (void)dealloc;
- (id)initWithOriginalImage:(id)arg1 withDelegate:(id)arg2 withCurrentViewController:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

