//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMObject.h"

@interface EditVideoUtil : MMObject
{
}

+ (void)saveEditedVideoByFilePath:(id)arg1;
+ (void)saveEditedVideo:(id)arg1;
+ (_Bool)isNeedSaveEditedVideo;
+ (id)getEditVideoThumbFilePathByUrl:(id)arg1;
+ (id)getEditVideoFilePathByUrl:(id)arg1;
+ (id)getAssetTmpDirByUrl:(id)arg1;
+ (id)getEditVideoTmpDir;

@end

