//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMUIView.h"

@class UIButton;
@protocol EditImageCropToolBarDelegate;

@interface EditImageCropToolBarView : MMUIView
{
    _Bool _revertBtnEnable;
    id <EditImageCropToolBarDelegate> _delegate;
    UIButton *_doneBtn;
    UIButton *_cancelBtn;
    UIButton *_revertBtn;
    UIButton *_rotateBtn;
}

@property(retain, nonatomic) UIButton *_rotateBtn; // @synthesize _rotateBtn;
@property(retain, nonatomic) UIButton *_revertBtn; // @synthesize _revertBtn;
@property(retain, nonatomic) UIButton *_cancelBtn; // @synthesize _cancelBtn;
@property(retain, nonatomic) UIButton *_doneBtn; // @synthesize _doneBtn;
@property(nonatomic) __weak id <EditImageCropToolBarDelegate> _delegate; // @synthesize _delegate;
- (void).cxx_destruct;
- (void)hideRotateBtn:(_Bool)arg1 withAnimation:(_Bool)arg2;
- (void)canRevertEnable:(_Bool)arg1;
- (id)hitTest:(struct CGPoint)arg1 withEvent:(id)arg2;
- (void)layoutSubviews;
- (id)init;

@end

