//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMObject.h"

@interface EmoticonReportData : MMObject
{
}

+ (void)ReportSendGifWithDatalength:(unsigned int)arg1 md5:(id)arg2 scene:(unsigned long long)arg3;
+ (void)ReportSelectGifFailedWithDatalength:(unsigned int)arg1 scene:(unsigned long long)arg2;
+ (void)ReportEmoticonAction:(unsigned long long)arg1 scene:(unsigned long long)arg2 messageWrap:(id)arg3;
+ (void)ReportEmoticonDownloadFromQrcode;
+ (void)ReportEmoticonDownloadFromNodeView;
+ (void)ReportEmoticonDownloadFromSns;
+ (void)ReportEmoticonDownloadFromPreview;
+ (void)ReportEmoticonBoardShowClick;

@end

