//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMObject.h"

@class EnterpriseBrandAttr;

@interface EnterpriseBrandAttrCacheItem : MMObject
{
    unsigned int _updateTime;
    EnterpriseBrandAttr *_attr;
}

@property(nonatomic) unsigned int updateTime; // @synthesize updateTime=_updateTime;
@property(retain, nonatomic) EnterpriseBrandAttr *attr; // @synthesize attr=_attr;
- (void).cxx_destruct;

@end

