//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMObject.h"

@class FBSDKLoginManager;

@interface FacebookAuth : MMObject
{
    int m_uiFacebookUsageType;
    FBSDKLoginManager *m_fbLogin;
}

@property(nonatomic) int m_uiFacebookUsageType; // @synthesize m_uiFacebookUsageType;
- (void).cxx_destruct;
- (void)reAuth;
- (void)requestNewPermission;
- (void)tryAuth;
- (void)clearToken;
- (id)getAccessToken;
- (void)SaveData;
- (void)fbDidExtendToken;
- (void)fbDidNotLogin:(_Bool)arg1;
- (void)fbDidLogin;
- (id)init;

@end

