//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMObject.h"

#import "AVCaptureVideoDataOutputSampleBufferDelegate-Protocol.h"
#import "SPXAudioRecorderDelegate-Protocol.h"

@class AVCaptureDeviceInput, AVCaptureSession, AVCaptureVideoDataOutput, AVCaptureVideoPreviewLayer, FaceProHandle, FaceRecogReporterFaceErrCounter, FaceRecogReporterFaceTimeMeter, FaceRecogVideoWriter, MMTimer, NSObject, NSString, SPXAudioRecorder;
@protocol FaceRecogProcessorDelegate, OS_dispatch_queue;

@interface FaceRecogProcessor : MMObject <AVCaptureVideoDataOutputSampleBufferDelegate, SPXAudioRecorderDelegate>
{
    _Bool _userCancel;
    _Bool _canChangeToReadNumber;
    _Bool _hadDetectFaceOK;
    _Bool _hadMakeUIChanged;
    unsigned int _scene;
    unsigned int _voiceId;
    float _maxMovieDuration;
    id <FaceRecogProcessorDelegate> _delegate;
    FaceRecogReporterFaceTimeMeter *_timeMeter;
    FaceRecogReporterFaceErrCounter *_errCounter;
    FaceProHandle *_liveDetector;
    AVCaptureSession *_captureSession;
    AVCaptureDeviceInput *_videoInput;
    AVCaptureVideoDataOutput *_videoOutput;
    NSObject<OS_dispatch_queue> *_liveDetectQueue;
    NSObject<OS_dispatch_queue> *_captureQueue;
    NSObject<OS_dispatch_queue> *_videoWriterQueue;
    AVCaptureVideoPreviewLayer *_previewLayer;
    SPXAudioRecorder *_spxRecorder;
    FaceRecogVideoWriter *_videoWriter;
    MMTimer *_detectFaceTimer;
    unsigned long long _bioId;
    NSString *_readingNumbers;
    long long _currentMotion;
    unsigned long long _audioTimeStamp;
    unsigned long long _videoTimeStamp;
    struct CGAffineTransform _videoTrans;
}

@property(nonatomic) struct CGAffineTransform videoTrans; // @synthesize videoTrans=_videoTrans;
@property(nonatomic) float maxMovieDuration; // @synthesize maxMovieDuration=_maxMovieDuration;
@property(nonatomic) unsigned long long videoTimeStamp; // @synthesize videoTimeStamp=_videoTimeStamp;
@property(nonatomic) unsigned long long audioTimeStamp; // @synthesize audioTimeStamp=_audioTimeStamp;
@property(nonatomic) _Bool hadMakeUIChanged; // @synthesize hadMakeUIChanged=_hadMakeUIChanged;
@property(nonatomic) _Bool hadDetectFaceOK; // @synthesize hadDetectFaceOK=_hadDetectFaceOK;
@property(nonatomic) long long currentMotion; // @synthesize currentMotion=_currentMotion;
@property(copy, nonatomic) NSString *readingNumbers; // @synthesize readingNumbers=_readingNumbers;
@property(nonatomic) unsigned long long bioId; // @synthesize bioId=_bioId;
@property(nonatomic) unsigned int voiceId; // @synthesize voiceId=_voiceId;
@property(nonatomic) _Bool canChangeToReadNumber; // @synthesize canChangeToReadNumber=_canChangeToReadNumber;
@property(retain, nonatomic) MMTimer *detectFaceTimer; // @synthesize detectFaceTimer=_detectFaceTimer;
@property(retain, nonatomic) FaceRecogVideoWriter *videoWriter; // @synthesize videoWriter=_videoWriter;
@property(retain, nonatomic) SPXAudioRecorder *spxRecorder; // @synthesize spxRecorder=_spxRecorder;
@property(retain, nonatomic) AVCaptureVideoPreviewLayer *previewLayer; // @synthesize previewLayer=_previewLayer;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *videoWriterQueue; // @synthesize videoWriterQueue=_videoWriterQueue;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *captureQueue; // @synthesize captureQueue=_captureQueue;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *liveDetectQueue; // @synthesize liveDetectQueue=_liveDetectQueue;
@property(nonatomic) unsigned int scene; // @synthesize scene=_scene;
@property(retain, nonatomic) AVCaptureVideoDataOutput *videoOutput; // @synthesize videoOutput=_videoOutput;
@property(retain, nonatomic) AVCaptureDeviceInput *videoInput; // @synthesize videoInput=_videoInput;
@property(retain, nonatomic) AVCaptureSession *captureSession; // @synthesize captureSession=_captureSession;
@property(retain, nonatomic) FaceProHandle *liveDetector; // @synthesize liveDetector=_liveDetector;
@property(retain, nonatomic) FaceRecogReporterFaceErrCounter *errCounter; // @synthesize errCounter=_errCounter;
@property(retain, nonatomic) FaceRecogReporterFaceTimeMeter *timeMeter; // @synthesize timeMeter=_timeMeter;
@property _Bool userCancel; // @synthesize userCancel=_userCancel;
@property(nonatomic) __weak id <FaceRecogProcessorDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)OnSPXPart:(id)arg1 Offset:(unsigned int)arg2 Len:(unsigned int)arg3 EndFlag:(unsigned int)arg4 ForceDelete:(_Bool)arg5;
- (_Bool)OnPrepareSendSPX:(id)arg1;
- (void)compressMovieWithExport;
- (void)tryMergeOutputVideo;
- (id)fixOrientation:(id)arg1;
- (id)getLastImageInFaceDetect:(struct opaqueCMSampleBuffer *)arg1;
- (void)saveLastSnapshot:(struct opaqueCMSampleBuffer *)arg1;
- (void)captureOutput:(id)arg1 didOutputSampleBuffer:(struct opaqueCMSampleBuffer *)arg2 fromConnection:(id)arg3;
- (void)processFrameUsingLiveDetector:(struct opaqueCMSampleBuffer *)arg1;
- (void)writeFrameIntoFile:(struct opaqueCMSampleBuffer *)arg1 isVideo:(_Bool)arg2;
- (id)genCaptureSession;
- (id)genCaptureVideoDataOutput;
- (id)genCaptureDeviceVideoInput;
- (id)getCamera:(long long)arg1;
- (void)releaseOutResultDataToFilePath:(id)arg1;
- (void)onRecordEnd;
- (_Bool)canChangeMotion;
- (void)markDetectFaceFulfillMinDetectTime;
- (id)getReadNumbers;
- (void)stopRecordingVideo;
- (void)startRecordingVideo;
- (_Bool)stopRecorder;
- (_Bool)startRecorder;
- (void)stopProcessor;
- (void)startProcessor;
- (id)getPreviewLayer;
- (_Bool)isRunning;
- (void)changeMotion;
- (void)initProcessor:(unsigned int)arg1;
- (_Bool)setupProcessParamters:(id)arg1 bioId:(unsigned long long)arg2;
- (void)initReportItem:(unsigned int)arg1;
- (void)dealloc;
- (id)initWithScene:(unsigned int)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

