//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMObject.h"

#import "FaceRecogConfigLogicDelegate-Protocol.h"
#import "FaceRecogProcessorDelegate-Protocol.h"
#import "FaceRecogUploadLogicDelegate-Protocol.h"
#import "FaceRecogVerifyViewControllerDelegate-Protocol.h"
#import "IDCHostMgrExt-Protocol.h"
#import "IRsaCertMgrExt-Protocol.h"

@class FaceRecogConfigLogic, FaceRecogProcessor, FaceRecogUploadLogic, FaceRecogVerifyViewController, NSMutableDictionary, NSString, UIViewController;
@protocol FaceRecogRsaVerifyHandlerDelegate;

@interface FaceRecogRsaVerifyHandler : MMObject <IDCHostMgrExt, IRsaCertMgrExt, FaceRecogProcessorDelegate, FaceRecogConfigLogicDelegate, FaceRecogUploadLogicDelegate, FaceRecogVerifyViewControllerDelegate>
{
    _Bool _isRetry;
    int _idcRedirectCount;
    id <FaceRecogRsaVerifyHandlerDelegate> _delegate;
    UIViewController *_currentViewController;
    FaceRecogVerifyViewController *_verifyVc;
    FaceRecogConfigLogic *_configFetcher;
    FaceRecogUploadLogic *_uploader;
    FaceRecogProcessor *_processor;
    NSString *_userTicket;
    NSMutableDictionary *_resultDic;
}

@property(nonatomic) int idcRedirectCount; // @synthesize idcRedirectCount=_idcRedirectCount;
@property(retain, nonatomic) NSMutableDictionary *resultDic; // @synthesize resultDic=_resultDic;
@property(copy, nonatomic) NSString *userTicket; // @synthesize userTicket=_userTicket;
@property(nonatomic) _Bool isRetry; // @synthesize isRetry=_isRetry;
@property(retain, nonatomic) FaceRecogProcessor *processor; // @synthesize processor=_processor;
@property(retain, nonatomic) FaceRecogUploadLogic *uploader; // @synthesize uploader=_uploader;
@property(retain, nonatomic) FaceRecogConfigLogic *configFetcher; // @synthesize configFetcher=_configFetcher;
@property(retain, nonatomic) FaceRecogVerifyViewController *verifyVc; // @synthesize verifyVc=_verifyVc;
@property(nonatomic) __weak UIViewController *currentViewController; // @synthesize currentViewController=_currentViewController;
@property(nonatomic) __weak id <FaceRecogRsaVerifyHandlerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)faceRecogDidEnterBackground;
- (void)faceRecogProcedureDidInterrupted;
- (void)doReportForUserCancel;
- (void)faceRecogDidFinishWithCode:(int)arg1 msg:(id)arg2 verifyResult:(id)arg3 canRetry:(_Bool)arg4;
- (void)finishedWithAuthorizationError:(id)arg1;
- (void)doFinishWithCode:(id)arg1;
- (void)onRsaVerifyFaceAgain:(id)arg1;
- (int)genErrCodeByResponse:(id)arg1;
- (void)handleRsaVerifyFace:(id)arg1;
- (void)RSAProtobufMessageReturn:(id)arg1 Event:(unsigned int)arg2;
- (void)doRsaVerify:(id)arg1;
- (void)startRecognizingProcedure;
- (void)doChangeToReadNum;
- (void)faceRecogDidRetry;
- (void)faceRecogDidClose;
- (void)faceRecogDidCancel;
- (void)faceRecogVerifyViewNumberViewDidEndAnimation;
- (void)faceRecogDidStartChangeToReadNumberMode;
- (void)procedureDidFailedReleaseOutResultData;
- (void)procedureDidGotFrameResult:(unsigned long long)arg1 failedType:(long long)arg2;
- (void)procedureDidStartUploadResultData;
- (void)procedureDidRecognizeFaceSuccess;
- (void)onUploadFaceResultFinish:(id)arg1;
- (void)onGetBioConfig:(id)arg1 failedCauseOf:(unsigned int)arg2 forScene:(unsigned int)arg3;
- (void)onGetBioConfig:(id)arg1 succeedForScene:(unsigned int)arg2;
- (void)doStartVerifyFaceProcedure;
- (void)doStartVerifyFace;
- (void)disMissAll:(_Bool)arg1;
- (void)startVerifyFace:(id)arg1;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

