//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class FavDataItemWrap, FavoritesItem, NSIndexPath, UITableView;

@protocol FavFilterViewControllerDelegate <NSObject>
- (void)onSelectFilterViewFavItem:(FavoritesItem *)arg1 tableView:(UITableView *)arg2 atIndexPath:(NSIndexPath *)arg3;

@optional
- (_Bool)bDisplayMode;
- (void)onSelectFilterViewFavDataItem:(FavDataItemWrap *)arg1 tableView:(UITableView *)arg2 atIndexPath:(NSIndexPath *)arg3;
@end

