//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMObject.h"

@class NSMutableString, NSString;

@interface FTSBussinessDetailInfo : MMObject
{
    NSString *_iconUrl;
    NSString *_desc;
    NSString *_descFormat;
    NSMutableString *_showDesc;
}

@property(retain, nonatomic) NSString *descFormat; // @synthesize descFormat=_descFormat;
@property(retain, nonatomic) NSString *desc; // @synthesize desc=_desc;
@property(retain, nonatomic) NSString *iconUrl; // @synthesize iconUrl=_iconUrl;
- (void).cxx_destruct;
- (id)getShowDescOfFullYear;
- (id)getShowDesc;
- (id)init;

@end

