//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "WCDBCoding-Protocol.h"

@class NSString;

@interface FTSFavSearchItem : NSObject <WCDBCoding>
{
    unsigned int localId;
    unsigned int updateTime;
    unsigned int FavItemReservedInt;
    NSString *searchTitle;
    NSString *searchDesc;
    NSString *searchSource;
    NSString *searchTag;
    NSString *FavItemReservedText;
    long long m___rowID;
}

+ (id)getWCDBTableHelperDictionary;
+ (const basic_string_a490aa4c *)getWCDBPrimaryColumnName;
+ (const struct WCDBIndexHelper *)getWCDBIndexArray;
+ (unsigned long long)getWCDBIndexArrayCount;
+ (const map_490096f0 *)getFileValueTagIndexMap;
+ (id)getFileValueTypeTable;
+ (const map_490096f0 *)getPackedValueTagIndexMap;
+ (id)getPackedValueTypeTable;
+ (const map_64c9abee *)getValueNameIndexMap;
+ (id)getValueTable;
+ (id)dummyObject;
@property(nonatomic) long long __rowID; // @synthesize __rowID=m___rowID;
@property(retain, nonatomic) NSString *FavItemReservedText; // @synthesize FavItemReservedText;
@property(nonatomic) unsigned int FavItemReservedInt; // @synthesize FavItemReservedInt;
@property(retain, nonatomic) NSString *searchTag; // @synthesize searchTag;
@property(retain, nonatomic) NSString *searchSource; // @synthesize searchSource;
@property(retain, nonatomic) NSString *searchDesc; // @synthesize searchDesc;
@property(retain, nonatomic) NSString *searchTitle; // @synthesize searchTitle;
@property(nonatomic) unsigned int updateTime; // @synthesize updateTime;
@property(nonatomic) unsigned int localId; // @synthesize localId;
- (void).cxx_destruct;
@property(readonly, copy) NSString *description;
- (void)simplifyForFTS;
- (void)copyFromItem:(id)arg1;
- (_Bool)isEqual:(id)arg1;
- (long long)compareSearchItemAscending:(id)arg1;
- (id)init;
- (const map_490096f0 *)getValueTagIndexMap;
- (id)getValueTypeTable;
- (const WCDBCondition_22fabacd *)db_FavItemReservedText;
- (const WCDBCondition_c6db074e *)db_FavItemReservedInt;
- (const WCDBCondition_22fabacd *)db_searchTag;
- (const WCDBCondition_22fabacd *)db_searchSource;
- (const WCDBCondition_22fabacd *)db_searchDesc;
- (const WCDBCondition_22fabacd *)db_searchTitle;
- (const WCDBCondition_c6db074e *)db_updateTime;
- (const WCDBCondition_c6db074e *)db_localId;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

