//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class FTSDB, NSMutableDictionary, NSRecursiveLock;

@interface FTSMessageDB : NSObject
{
    FTSDB *_database;
    NSRecursiveLock *_lock;
    NSMutableDictionary *_dicValidUserName;
    NSMutableDictionary *_dicValidUserNameId;
    NSMutableDictionary *_dicInvalidUserNameId;
}

@property(retain, nonatomic) FTSDB *database; // @synthesize database=_database;
- (void).cxx_destruct;
- (_Bool)deleteInvalidRowsInChatTable:(unsigned int)arg1;
- (_Bool)hasInvalidRowsInChatTable;
- (unsigned int)getPreCursorMesId:(id)arg1;
- (unsigned int)getNextCursorMesId:(id)arg1;
- (id)queryText:(id)arg1 limit:(unsigned int)arg2 searchAll:(id *)arg3;
- (id)queryText:(id)arg1;
- (_Bool)deleteRowInChatTable:(id)arg1 arrMsgWrap:(id)arg2;
- (_Bool)deleteRowInChatTable:(id)arg1 msgWrap:(id)arg2;
- (_Bool)deleteRowInUserNameIDTable:(unsigned int)arg1;
- (_Bool)updateInvalidUserPreCursorMesId:(unsigned int)arg1 cursorMesId:(unsigned int)arg2;
- (_Bool)updateUserPreCursorMesId:(id)arg1 cursorMesId:(unsigned int)arg2;
- (_Bool)updateUserNextCursorMesId:(id)arg1 cursorMesId:(unsigned int)arg2;
- (_Bool)updateUserNameInvalid:(id)arg1;
- (_Bool)insertRowsInChatTable:(id)arg1 arrMsgWrap:(id)arg2;
- (_Bool)insertRowInChatTable:(id)arg1 msgWrap:(id)arg2;
- (_Bool)insertNewRowInUserNameIDTable:(id)arg1 lastMsg:(id)arg2;
- (void)tryCacheUserNameIdTable;
- (id)tryGetValidIndexItemByUserNameId:(unsigned int)arg1;
- (id)tryGetValidIndexItemByUserName:(id)arg1;
- (_Bool)createAllTable;
- (void)reloadDB;
- (void)initDB:(id)arg1;
- (void)dealloc;
- (id)init;

@end

