//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "WCDBCoding-Protocol.h"

@class NSString;

@interface GameCenterMsgDbModel : NSObject <WCDBCoding>
{
    _Bool showInMsgCenter;
    _Bool unRead;
    unsigned int localId;
    unsigned int type;
    unsigned int createTime;
    unsigned int recvTime;
    NSString *svrMsgId;
    NSString *content;
    NSString *mergeId;
    long long m___rowID;
}

+ (const basic_string_a490aa4c *)getWCDBPrimaryColumnName;
+ (const struct WCDBIndexHelper *)getWCDBIndexArray;
+ (unsigned long long)getWCDBIndexArrayCount;
+ (const map_490096f0 *)getFileValueTagIndexMap;
+ (id)getFileValueTypeTable;
+ (const map_490096f0 *)getPackedValueTagIndexMap;
+ (id)getPackedValueTypeTable;
+ (const map_64c9abee *)getValueNameIndexMap;
+ (id)getValueTable;
+ (id)dummyObject;
@property(nonatomic) long long __rowID; // @synthesize __rowID=m___rowID;
@property(nonatomic) unsigned int recvTime; // @synthesize recvTime;
@property(retain, nonatomic) NSString *mergeId; // @synthesize mergeId;
@property(nonatomic) _Bool unRead; // @synthesize unRead;
@property(nonatomic) _Bool showInMsgCenter; // @synthesize showInMsgCenter;
@property(nonatomic) unsigned int createTime; // @synthesize createTime;
@property(retain, nonatomic) NSString *content; // @synthesize content;
@property(nonatomic) unsigned int type; // @synthesize type;
@property(retain, nonatomic) NSString *svrMsgId; // @synthesize svrMsgId;
@property(nonatomic) unsigned int localId; // @synthesize localId;
- (void).cxx_destruct;
- (id)initWithGameCenterMsg:(id)arg1;
- (const map_490096f0 *)getValueTagIndexMap;
- (id)getValueTypeTable;
- (const WCDBCondition_c6db074e *)db_recvTime;
- (const WCDBCondition_22fabacd *)db_mergeId;
- (const WCDBCondition_d7690721 *)db_unRead;
- (const WCDBCondition_d7690721 *)db_showInMsgCenter;
- (const WCDBCondition_c6db074e *)db_createTime;
- (const WCDBCondition_22fabacd *)db_content;
- (const WCDBCondition_c6db074e *)db_type;
- (const WCDBCondition_22fabacd *)db_svrMsgId;
- (const WCDBCondition_c6db074e *)db_localId;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

