//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GCDWebServerDataRequest.h"

@class NSDictionary;

@interface GCDWebServerURLEncodedFormRequest : GCDWebServerDataRequest
{
    NSDictionary *_arguments;
}

+ (id)mimeType;
@property(readonly, nonatomic) NSDictionary *arguments; // @synthesize arguments=_arguments;
- (void).cxx_destruct;
- (id)description;
- (_Bool)close:(id *)arg1;

@end

