//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GPUImageTwoInputCrossTextureSamplingFilter.h"

@class GPUImageFramebuffer;

@interface GPUImagePoissonBlendFilter : GPUImageTwoInputCrossTextureSamplingFilter
{
    int mixUniform;
    GPUImageFramebuffer *secondOutputFramebuffer;
    double _mix;
    unsigned long long _numIterations;
}

@property(nonatomic) unsigned long long numIterations; // @synthesize numIterations=_numIterations;
@property(nonatomic) double mix; // @synthesize mix=_mix;
- (void).cxx_destruct;
- (void)renderToTextureWithVertices:(const float *)arg1 textureCoordinates:(const float *)arg2;
- (id)init;

@end

