//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class CaptureVideoInfo, ImageInfo, MMAsset, NSData, NSString, SightDraft, UIImage, UIViewController;

@protocol ImageControllerDelegate <NSObject>
- (_Bool)CanSendVideoMsg;
- (_Bool)CanSendMultiImage;
- (_Bool)CanSendOriginalImage;
- (UIViewController *)getViewController;

@optional
- (void)processInsertedGifData:(NSData *)arg1;
- (_Bool)CanSendEmoticonMessage;
- (void)processImageControllerDidCancel:(unsigned long long)arg1;
- (void)CameraControllerDidTakeSightImage:(UIImage *)arg1 withFrontCamera:(_Bool)arg2;
- (void)CameraControllerDidTakeSight:(SightDraft *)arg1;
- (void)CameraControllerDidTakeVideo:(CaptureVideoInfo *)arg1;
- (NSString *)chatUserNameForSightStatistics;
- (void)processImageDidFinish;
- (void)processImageDidCancel;
- (void)processInsertedImage:(UIImage *)arg1 withData:(NSData *)arg2 ImageInfo:(ImageInfo *)arg3;
- (void)processInsertedAsset:(MMAsset *)arg1;
@end

