//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@protocol IMessageNodeStatusExt <NSObject>

@optional
- (void)onMessageDownloadVideoFail;
- (void)onMessageDownloadVideoExpired;
- (void)onMessageDownloadAppAttachFail;
- (void)onMessageDownloadAppAttachExpired;
- (void)onMessageDownloadThumbImageOK;
- (void)onMessageUpdateStatus;
- (void)onMessageStopPlaying;
- (void)onMessageStartPlaying;
@end

