//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMUIViewController.h"

#import "ContactSelectViewDelegate-Protocol.h"
#import "IOplogExt-Protocol.h"
#import "InfrequentContactsDataLogicDelegate-Protocol.h"
#import "WCActionSheetDelegate-Protocol.h"
#import "WCFacadeExt-Protocol.h"

@class InfrequentContactView, InfrequentContactsDataLogic, MMUILabel, NSMutableArray, NSMutableDictionary, NSString, UIActivityIndicatorView, UIButton, UILabel, UIView;

@interface InfrequentContactListViewController : MMUIViewController <ContactSelectViewDelegate, InfrequentContactsDataLogicDelegate, WCActionSheetDelegate, IOplogExt, WCFacadeExt>
{
    InfrequentContactView *m_selectView;
    UIView *m_bottomBar;
    UIButton *m_selectAllBtn;
    UIButton *m_deleteBtn;
    UIButton *m_moreBtn;
    MMUILabel *m_titleLable;
    UILabel *m_label;
    UIActivityIndicatorView *m_activityIndicatorView;
    NSMutableDictionary *m_dicDeletingContacts;
    NSMutableArray *m_arrDeleteFailContacts;
    NSMutableArray *m_arrDeleteOKContacts;
    NSMutableArray *m_arrDeleteIndex;
    InfrequentContactsDataLogic *m_dataLogic;
    _Bool m_bMultiSelect;
    unsigned int m_uiSingleDelCount;
    unsigned int m_uiMultiDelCount;
    unsigned int m_uiSingleLookInfoCount;
    unsigned int m_uiMultiSnsBlackCount;
    unsigned int m_uiMultiLookInfoCount;
    unsigned int m_uiMultiSnsIgnoreCount;
}

- (void).cxx_destruct;
- (void)onInfrequentContactInitDataDone;
- (_Bool)onFilterContactCandidate:(id)arg1;
- (void)actionMenu:(long long)arg1 tableView:(id)arg2 indexPath:(id)arg3 contact:(id)arg4;
- (void)makeMoreMenu:(id)arg1 cell:(id)arg2;
- (void)onSelectContact:(id)arg1;
- (void)onViewContact:(id)arg1;
- (void)viewWillPop:(_Bool)arg1;
- (void)actionSheet:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)onMore;
- (void)onWCGroupUpdated;
- (void)onDeleteDone;
- (void)oplogRet:(int)arg1 errMsg:(id)arg2 eventID:(unsigned int)arg3 cgiWrap:(id)arg4;
- (void)onDelete;
- (void)onSelectAll;
- (void)onCancelMultiSelect;
- (void)onMultiSelect;
- (void)animateUpdateView;
- (void)reloadTableView;
- (void)onContactsDataNeedChange;
- (void)initView;
- (void)upadteData;
- (void)makeTopView;
- (void)initBottomArea;
- (void)upadteBarView;
- (void)onCancelBack;
- (void)viewDidLoad;
- (void)reportData;
- (void)dealloc;
- (id)initWithDataLogic:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

