//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMObject.h"

#import "ContactInitLogicExt-Protocol.h"
#import "MessageObserverDelegate-Protocol.h"

@class ContactInitLogic, MMTimer, NSString;
@protocol initLogicControllerDelegate;

@interface InitLogicController : MMObject <ContactInitLogicExt, MessageObserverDelegate>
{
    id <initLogicControllerDelegate> m_delegate;
    vector_a9c0768e m_vecMesssageIdToListen;
    _Bool m_bIsIniting;
    _Bool m_bFromReg;
    MMTimer *m_percenTimer;
    unsigned int m_curPercent;
    unsigned int m_uiEventID;
    ContactInitLogic *m_contactInitLogic;
    _Bool m_useInitContact;
}

@property(nonatomic) _Bool m_bFromReg; // @synthesize m_bFromReg;
@property(readonly, nonatomic) _Bool m_bIsIniting; // @synthesize m_bIsIniting;
@property(nonatomic) __weak id <initLogicControllerDelegate> m_delegate; // @synthesize m_delegate;
- (id).cxx_construct;
- (void).cxx_destruct;
- (void)onContactInitSuccess;
- (void)onContactInitFail;
- (void)onContactInitProcessUpdate:(unsigned int)arg1;
- (void)retryInitContact;
- (void)tryInitContact;
- (void)MessageReturn:(unsigned int)arg1 MessageInfo:(id)arg2 Event:(unsigned int)arg3;
- (void)stopIniting:(unsigned int)arg1;
- (void)dealloc;
- (_Bool)startInit;
- (void)stopPercentTimer;
- (void)startPercentTimer;
- (void)onPercentTimer;
- (void)percentIniting;
- (unsigned int)getCurNetworkStatus;
- (_Bool)initInternal;
- (_Bool)isNeedInit;
- (_Bool)isCanShowWhatsNew;
- (id)init;
- (void)initMessageIdToListen;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

