//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

@class CQQContact, NSString;

@protocol IQQContactMgrExt

@optional
- (void)onSyncQQContactEnd;
- (void)onDeleteQQContact:(NSString *)arg1;
- (void)onModifyQQContact:(CQQContact *)arg1;
- (void)onNewQQContact:(CQQContact *)arg1;
- (void)onModifyQQContactHeadImage:(NSString *)arg1;
@end

