//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "CBaseContact.h"

#import "WCDBCoding-Protocol.h"

@class NSString;

@interface KFContact : CBaseContact <WCDBCoding>
{
    _Bool headImgUpdateFlag;
    unsigned int updateTime;
    NSString *kfOpenId;
    NSString *brand;
    NSString *headImageUrl;
    NSString *nickName;
    long long m___rowID;
}

+ (const basic_string_a490aa4c *)getWCDBPrimaryColumnName;
+ (const struct WCDBIndexHelper *)getWCDBIndexArray;
+ (unsigned long long)getWCDBIndexArrayCount;
+ (const map_490096f0 *)getFileValueTagIndexMap;
+ (id)getFileValueTypeTable;
+ (const map_490096f0 *)getPackedValueTagIndexMap;
+ (id)getPackedValueTypeTable;
+ (const map_64c9abee *)getValueNameIndexMap;
+ (id)getValueTable;
+ (id)dummyObject;
@property(nonatomic) long long __rowID; // @synthesize __rowID=m___rowID;
@property(nonatomic) _Bool headImgUpdateFlag; // @synthesize headImgUpdateFlag;
@property(nonatomic) unsigned int updateTime; // @synthesize updateTime;
@property(retain, nonatomic) NSString *nickName; // @synthesize nickName;
@property(retain, nonatomic) NSString *headImageUrl; // @synthesize headImageUrl;
@property(retain, nonatomic) NSString *brand; // @synthesize brand;
@property(retain, nonatomic) NSString *kfOpenId; // @synthesize kfOpenId;
- (void).cxx_destruct;
- (const map_490096f0 *)getValueTagIndexMap;
- (id)getValueTypeTable;
- (const WCDBCondition_d7690721 *)db_headImgUpdateFlag;
- (const WCDBCondition_9620f531 *)db_updateTime;
- (const WCDBCondition_22fabacd *)db_nickName;
- (const WCDBCondition_22fabacd *)db_headImageUrl;
- (const WCDBCondition_22fabacd *)db_brand;
- (const WCDBCondition_22fabacd *)db_kfOpenId;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

