//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@protocol MMCommonAdapterDelegate;

@interface MMCommonAdapter : NSObject
{
    id <MMCommonAdapterDelegate> _m_delegate;
}

+ (id)SharedInstance;
+ (void)SetupWithDelegate:(id)arg1;
@property __weak id <MMCommonAdapterDelegate> m_delegate; // @synthesize m_delegate=_m_delegate;
- (void).cxx_destruct;

@end

