//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@protocol MMDBPerfromStrategyDelegate;

@interface MMDBPerformStrategyHandler : NSObject
{
    id <MMDBPerfromStrategyDelegate> _m_delegate;
}

@property(nonatomic) __weak id <MMDBPerfromStrategyDelegate> m_delegate; // @synthesize m_delegate=_m_delegate;
- (void).cxx_destruct;
- (void)saveLocalStrategy:(id)arg1;
- (void)LoadLocalStrategy;
- (void)ReceiveStrategyContent:(id)arg1;

@end

