//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "PBCoding-Protocol.h"

@class NSString;

@interface MMDBPerformanceSQLRecord : NSObject <PBCoding>
{
    unsigned int tid;
    unsigned int lastTime;
    unsigned int timeStamp;
    NSString *sql;
}

+ (void)initialize;
@property(nonatomic) unsigned int timeStamp; // @synthesize timeStamp;
@property(nonatomic) unsigned int lastTime; // @synthesize lastTime;
@property(retain, nonatomic) NSString *sql; // @synthesize sql;
@property(nonatomic) unsigned int tid; // @synthesize tid;
- (void).cxx_destruct;
- (id)sqlContentFromSqlRecord;
- (unsigned int)calculateSize;
@property(readonly, copy) NSString *description;
- (const map_490096f0 *)getValueTagIndexMap;
- (id)getValueTypeTable;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

