//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface MMDicOwners : NSObject
{
    map_9e4616a2 *m_mapOwnerMapDelegateProxy;
}

@property(nonatomic) map_9e4616a2 *m_mapOwnerMapDelegateProxy; // @synthesize m_mapOwnerMapDelegateProxy;
- (void)dealloc;
- (id)init;

@end

