//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

@class MMMusicPlayerErrInfo;

@protocol MMMusicPlayerExt

@optional
- (void)onMusicPlayErrorStop:(MMMusicPlayerErrInfo *)arg1;
- (void)onMusicPlayFinish;
- (void)onMusicSeekEnd;
- (void)onMusicPrepareSeeking;
- (void)onMusicInitAlready;
- (void)onDataBuffering:(double)arg1;
- (void)onNeedSetPlayPercent;
- (void)onNewSeekTime:(double)arg1;
- (void)onForceStopMusic;
- (void)onMusicPlayStatusChanged;
- (void)onLevelMeterPeak:(float)arg1;
@end

