//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface MMService : NSObject
{
    _Bool m_isServiceRemoved;
    _Bool m_isServicePersistent;
}

@property _Bool m_isServicePersistent; // @synthesize m_isServicePersistent;
@property _Bool m_isServiceRemoved; // @synthesize m_isServiceRemoved;

@end

