//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMWebViewPluginBase.h"

#import "IMusicPlayerExt-Protocol.h"

@class NSString;

@interface MMWebViewPlugin_MusicEvent : MMWebViewPluginBase <IMusicPlayerExt>
{
    _Bool _isNotifyMusicStateChange;
    _Bool _isSeeking;
    NSString *_curMusicId;
    NSString *_curMusicSrc;
    NSString *_curMusicSrcId;
}

@property(nonatomic) _Bool isSeeking; // @synthesize isSeeking=_isSeeking;
@property(nonatomic) _Bool isNotifyMusicStateChange; // @synthesize isNotifyMusicStateChange=_isNotifyMusicStateChange;
@property(retain, nonatomic) NSString *curMusicSrcId; // @synthesize curMusicSrcId=_curMusicSrcId;
@property(retain, nonatomic) NSString *curMusicSrc; // @synthesize curMusicSrc=_curMusicSrc;
@property(retain, nonatomic) NSString *curMusicId; // @synthesize curMusicId=_curMusicId;
- (void).cxx_destruct;
- (_Bool)isUrl:(id)arg1 HostEqualTo:(id)arg2;
- (void)onMusicStopError:(id)arg1 errInfo:(id)arg2;
- (void)sendMusicPlayEventIfNeed:(id)arg1 musicInfo:(id)arg2;
- (void)onMusicPlayFinish:(id)arg1;
- (void)onMusicSeekEnd:(id)arg1;
- (void)onMusicSeeking:(id)arg1;
- (void)onMusicInitAlready:(id)arg1;
- (void)onPlayMusic:(id)arg1 fromScene:(int)arg2;
- (void)onMusicPlayStatusChanged;
- (void)beginObserveMusicStateChange:(id)arg1 musicSrc:(id)arg2 srcId:(id)arg3;
- (id)init;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

