//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "FTSWebSearchDataSource-Protocol.h"
#import "UIScrollViewDelegate-Protocol.h"
#import "UISearchBarDelegate-Protocol.h"
#import "UISearchDisplayDelegate-Protocol.h"
#import "WASearchFromGlobalProxyDelegate-Protocol.h"
#import "WSContactSearchLogicDelegate-Protocol.h"
#import "WSJSEventHandleDelegate-Protocol.h"
#import "WSSuggestionLogicDelegate-Protocol.h"
#import "WSTagSearchDelegate-Protocol.h"

@class FTSWebSearchMgr, MMTagSearchBar, MMUIViewController, NSDictionary, NSMutableArray, NSMutableDictionary, NSString, UIButton, UIColor, UIImageView, UISearchDisplayController, UITextField, UIView, WASearchFromGlobalProxy, WSContactSearchLogic, WSJSEventHandler, WSResultViewLogic, WSSuggestionLogic, WSTagSearchLogic;
@protocol MMWebSearchViewDelegate;

@interface MMWebSearchController : NSObject <UISearchBarDelegate, UISearchDisplayDelegate, UIScrollViewDelegate, WSJSEventHandleDelegate, FTSWebSearchDataSource, WSTagSearchDelegate, WSContactSearchLogicDelegate, WASearchFromGlobalProxyDelegate, WSSuggestionLogicDelegate>
{
    NSString *_lastShouldChangedFormatQuery;
    MMUIViewController *_contentVC;
    FTSWebSearchMgr *_webSearchMgr;
    NSMutableArray *_arrResultViews;
    WSResultViewLogic *_resultViewLogic;
    NSString *_query;
    UIImageView *_searchBarWrap;
    UIView *_searchBarSuperView;
    UIButton *_backButton;
    WSJSEventHandler *_jsEventHandler;
    WSContactSearchLogic *_searchContactLogic;
    WSTagSearchLogic *_tagSearchLogic;
    WSSuggestionLogic *_nativeSuggestionLogic;
    int _initSearchScene;
    int _searchContext;
    unsigned long long _mainBusinessType;
    unsigned long long _detailSearchType;
    NSString *_searchID;
    NSString *_browsingTID;
    NSMutableArray *_arrDeletedTID;
    UIImageView *_bottomViewShadow;
    _Bool _hasMoving;
    double _moveStartOffset;
    double _moveCurOffset;
    double _moveContentOffsetY;
    double _searchTextFieldNormalWidth;
    struct CGSize _searchIconDefaultSize;
    _Bool _bHasStartRetrieveLocation;
    _Bool _bForbidSearchControllerCallBack;
    _Bool _isWeAppSearch;
    WASearchFromGlobalProxy *_weAppSearchProxy;
    _Bool _alwaysForbidVCInteractivePop;
    _Bool _bSkipBackButtonAtFirst;
    _Bool _bUseCustomSearchInput;
    _Bool _bUseBlurViewBeforeSearch;
    _Bool _bNeedsLuanchingWebViewBackgroundColor;
    id <MMWebSearchViewDelegate> _delegate;
    NSDictionary *_urlParams;
    UIView *_viewForBlur;
    UIColor *_luanchingWebViewBackgroundColor;
    UIView *_resultContainerView;
    UIView *_blurView;
    UISearchDisplayController *_searchDisplayController;
    MMTagSearchBar *_searchBar;
    UITextField *_searchTextField;
    UIImageView *_searchLeftIcon;
    UIView *_searchPromtLabel;
    NSMutableDictionary *_widgetViewCache;
}

@property(retain, nonatomic) NSMutableDictionary *widgetViewCache; // @synthesize widgetViewCache=_widgetViewCache;
@property(retain, nonatomic) UIView *searchPromtLabel; // @synthesize searchPromtLabel=_searchPromtLabel;
@property(retain, nonatomic) UIImageView *searchLeftIcon; // @synthesize searchLeftIcon=_searchLeftIcon;
@property(retain, nonatomic) UITextField *searchTextField; // @synthesize searchTextField=_searchTextField;
@property(readonly, nonatomic) FTSWebSearchMgr *webSearchMgr; // @synthesize webSearchMgr=_webSearchMgr;
@property(retain, nonatomic) MMTagSearchBar *searchBar; // @synthesize searchBar=_searchBar;
@property(retain, nonatomic) UISearchDisplayController *searchDisplayController; // @synthesize searchDisplayController=_searchDisplayController;
@property(readonly, nonatomic) UIView *blurView; // @synthesize blurView=_blurView;
@property(readonly, nonatomic) UIView *resultContainerView; // @synthesize resultContainerView=_resultContainerView;
@property(readonly, nonatomic) UIView *searchBarWrap; // @synthesize searchBarWrap=_searchBarWrap;
@property(retain, nonatomic) UIColor *luanchingWebViewBackgroundColor; // @synthesize luanchingWebViewBackgroundColor=_luanchingWebViewBackgroundColor;
@property(nonatomic) _Bool bNeedsLuanchingWebViewBackgroundColor; // @synthesize bNeedsLuanchingWebViewBackgroundColor=_bNeedsLuanchingWebViewBackgroundColor;
@property(nonatomic) __weak UIView *viewForBlur; // @synthesize viewForBlur=_viewForBlur;
@property(nonatomic) _Bool bUseBlurViewBeforeSearch; // @synthesize bUseBlurViewBeforeSearch=_bUseBlurViewBeforeSearch;
@property(retain, nonatomic) NSDictionary *urlParams; // @synthesize urlParams=_urlParams;
@property(nonatomic) _Bool bUseCustomSearchInput; // @synthesize bUseCustomSearchInput=_bUseCustomSearchInput;
@property(nonatomic) _Bool bSkipBackButtonAtFirst; // @synthesize bSkipBackButtonAtFirst=_bSkipBackButtonAtFirst;
@property(nonatomic) _Bool alwaysForbidVCInteractivePop; // @synthesize alwaysForbidVCInteractivePop=_alwaysForbidVCInteractivePop;
@property(nonatomic) __weak id <MMWebSearchViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)onUpdateSuggestion;
- (id)getNativeSuggestionId;
- (void)clearHistoryOperation;
- (id)getHistoryResult;
- (id)getSuggestionResult;
- (void)deleteHistorySuggestion:(id)arg1;
- (void)reportNativeSugFill:(id)arg1 withParams:(id)arg2;
- (void)reportNativeSugClick:(id)arg1 withParams:(id)arg2;
- (void)mainContentQueryChanged:(id)arg1;
- (void)onSearchInputSwitchSearchContext:(id)arg1;
- (void)onSearchInputClickKeyboardCancel;
- (_Bool)onSearchInputClickBack;
- (void)onSearchInputClickCancel:(unsigned long long)arg1;
- (void)onSearchInputClickSearch:(id)arg1;
- (void)onSearchInputTextChanged:(id)arg1;
- (void)onSearchInputBeginEditting:(id)arg1;
- (void)onWAProxyCGISearch:(id)arg1;
- (void)onWAProxyWillBeginDetailSearch:(id)arg1;
- (void)onWAProxySearchInputChanged:(id)arg1;
- (void)onWAProxyHideKeyboard;
- (void)onReturnWSContactResult:(id)arg1;
- (void)onTagSearchBarInfoChangedToNotify:(id)arg1;
- (void)tryAsyncSearchContact:(id)arg1;
- (unsigned int)getCorrectLevel:(id)arg1;
- (void)pushToKeywordStack:(id)arg1;
- (void)onPreSearch:(id)arg1 bizType:(unsigned long long)arg2;
- (void)onOpenWAWidgetLogViewWithParams:(id)arg1;
- (void)onUpdateWAWidgetWithParams:(id)arg1;
- (void)onRemoveWAWidgetWithParams:(id)arg1;
- (id)onInsertWAWidgetWithParams:(id)arg1;
- (void)didFinishLoadWebView:(id)arg1;
- (void)onSwitchSearchContext:(id)arg1;
- (void)onInsertHistoryOperation:(id)arg1;
- (void)onClearHistoryOperation:(id)arg1;
- (void)onRequestLocalSuggestion:(id)arg1;
- (void)onWSMusicStatusChanged:(id)arg1;
- (void)currentFriendScene:(unsigned int *)arg1 withParams:(id)arg2;
- (void)onDeleteBrowsingSnsItemOnH5;
- (void)onBrowsingSnsItem:(id)arg1;
- (_Bool)checkBrowsingSnsItem:(id)arg1;
- (void)onClickRecmdWord:(id)arg1;
- (void)onLaunchDetailPageForWeApp:(id)arg1;
- (void)onLaunchDetailPage:(id)arg1;
- (void)onSearchInputChanged:(id)arg1;
- (void)enableSearchBar;
- (void)hideSearchKeyboard;
- (id)viewStacks;
- (unsigned long long)businessType;
- (id)query;
- (void)onRemoveDetailView;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (void)searchDisplayControllerDidEndSearch:(id)arg1;
- (void)searchDisplayControllerWillEndSearch:(id)arg1;
- (void)searchDisplayControllerDidBeginSearch:(id)arg1;
- (void)searchDisplayControllerWillBeginSearch:(id)arg1;
- (void)searchBarCancelButtonClicked:(id)arg1;
- (void)searchBarSearchButtonClicked:(id)arg1;
- (void)searchBar:(id)arg1 textDidChange:(id)arg2;
- (_Bool)searchBar:(id)arg1 shouldChangeTextInRange:(struct _NSRange)arg2 replacementText:(id)arg3;
- (void)searchBarTextDidBeginEditing:(id)arg1;
- (void)onTapBlurView;
- (void)cancelMoveDetailView;
- (void)moveDetailViewToRight;
- (void)updateMovingDetailView;
- (void)handlePanGestureForDetailView:(id)arg1;
- (void)popFromDetailSearch;
- (void)resetSearchIconFrame;
- (id)searchLeftView;
- (void)hideKeyboard;
- (void)enableButton:(id)arg1;
- (void)loadLocalHtmlForDetailPage:(id)arg1;
- (id)makeNewDetailView:(id)arg1;
- (void)willBeginDetailSearchOfWeApp:(id)arg1;
- (void)willBeginDetailSearch:(id)arg1 context:(int)arg2;
- (void)loadH5ForMainView;
- (double)getSearchTextFieldWidth;
- (void)beginSearch:(_Bool)arg1;
- (void)notifyPageOfQueryChanged:(id)arg1;
- (void)notifyPageOfSearchClick:(id)arg1;
- (void)asyncSearch:(id)arg1;
- (void)cancelSearch;
- (void)onClickSearchButton:(id)arg1;
- (int)currentWebSearchContext;
- (void)onBackBtnClick;
- (id)secondLastResultView;
- (id)currentResultView;
- (_Bool)isSupportLocalSuggestion;
- (_Bool)isSupportSuggestion;
- (_Bool)isMainViewForMixSearch;
- (_Bool)isSpecialTopBarMode;
- (_Bool)isSubSearch;
- (_Bool)isVerticalSearch;
- (void)initBackButton;
- (void)updateContentView;
- (void)updateSearchBarInfo;
- (void)initBlurView;
- (void)initResultView;
- (void)initSearchBar;
- (void)initView;
- (void)initNativeSuggestionLogic;
- (void)initContactSearchLogic;
- (void)initTagSearchLogic;
- (void)initSearchContext;
- (void)initWebSearchMgr;
- (void)initData;
- (void)startRetriveLocation;
- (void)clearSearchBarComponent;
- (void)clearResource;
- (void)cancelSearchAnimated:(_Bool)arg1;
- (void)prepareSearchAnimated:(_Bool)arg1;
- (void)dealloc;
- (id)initWithScene:(int)arg1 contentVC:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

