//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSDictionary, NSString, UIButton, UISearchDisplayController;

@protocol MMWebSearchViewDelegate <NSObject>

@optional
- (void)onUpdateNativeSuggestion;
- (void)onSearchReset;
- (void)onSearchBackToPreviousView;
- (void)onSearchLaunchNextViewWithBizType:(unsigned long long)arg1;
- (void)onSearchInputSetPlaceHolder:(NSDictionary *)arg1;
- (void)onSearchInputSetText:(NSString *)arg1 tagInfo:(NSDictionary *)arg2;
- (double)webSearchViewPosY;
- (void)onPreSearch:(NSString *)arg1 bizType:(unsigned long long)arg2;
- (void)didEndSearch:(UISearchDisplayController *)arg1;
- (void)willEndSearch:(UISearchDisplayController *)arg1;
- (void)didBeginSearch:(UISearchDisplayController *)arg1;
- (void)willBeginSearch:(UISearchDisplayController *)arg1;
- (void)onTapBlurEffectView;
- (void)onFinalBackButtonClick:(UIButton *)arg1;
@end

