//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMUIViewController.h"

#import "ForwardMessageLogicDelegate-Protocol.h"
#import "IRecordDownloadExt-Protocol.h"
#import "ImageScrollViewDelegate-Protocol.h"
#import "SessionSelectControllerDelegate-Protocol.h"
#import "UIDocumentInteractionControllerDelegate-Protocol.h"
#import "UIGestureRecognizerDelegate-Protocol.h"
#import "UIScrollViewDelegate-Protocol.h"
#import "WCActionSheetDelegate-Protocol.h"

@class ForwardMessageLogicController, ImageScrollView, MMProgressView, MsgRecordDataWrap, NSString, UIButton, UIDocumentInteractionController, UILabel, UITapGestureRecognizer, UIWebView;
@protocol MsgRecordFileDetailDelegate;

@interface MsgRecordFileDetailViewController : MMUIViewController <ForwardMessageLogicDelegate, UIScrollViewDelegate, UIGestureRecognizerDelegate, IRecordDownloadExt, ImageScrollViewDelegate, WCActionSheetDelegate, SessionSelectControllerDelegate, UIDocumentInteractionControllerDelegate>
{
    MsgRecordDataWrap *m_recordDataWrap;
    NSString *m_nsFilePath;
    NSString *m_nsFileName;
    unsigned int m_uiFileSize;
    _Bool m_bIsUnkownType;
    unsigned int m_uiFileType;
    MMProgressView *m_progressBar;
    UILabel *m_downloadLabel;
    UIButton *m_btnDownload;
    UILabel *m_downloadFail;
    UIButton *m_btnOpenByApp;
    UIDocumentInteractionController *m_vcDocument;
    ImageScrollView *m_imgPreview;
    id <MsgRecordFileDetailDelegate> m_delegate;
    NSString *m_tmpFilePath;
    UIWebView *m_webview;
    UITapGestureRecognizer *_singleTapRec;
    _Bool _bIsNaviBarHide;
    _Bool _bIsDisableTapRec;
    double lastOffset;
    ForwardMessageLogicController *m_forwardMsgLogic;
    _Bool m_shouldDelayOpenFile;
    _Bool m_hasAppear;
}

@property(nonatomic) __weak id <MsgRecordFileDetailDelegate> m_delegate; // @synthesize m_delegate;
@property(retain, nonatomic) MsgRecordDataWrap *m_recordDataWrap; // @synthesize m_recordDataWrap;
- (void).cxx_destruct;
- (void)scrollViewDidScroll:(id)arg1;
- (void)didRotateFromInterfaceOrientation:(long long)arg1;
- (void)setNaviBarHide:(_Bool)arg1 animation:(_Bool)arg2;
- (void)OnSingleTap:(id)arg1;
- (unsigned long long)supportedInterfaceOrientations;
- (id)getCurrentViewController;
- (void)actionSheet:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)onSingleTap:(id)arg1;
- (void)OnDownloadRecordMessagePart:(id)arg1 DataId:(id)arg2 PartLen:(unsigned int)arg3 TotalLen:(unsigned int)arg4;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)OnDownloadRecordMessageOK:(id)arg1 DataId:(id)arg2 bThumb:(_Bool)arg3;
- (void)OnDownloadRecordMessageFail:(id)arg1 DataId:(id)arg2;
- (void)OnDownloadRecordMessageExpired:(id)arg1 DataId:(id)arg2;
- (void)documentInteractionController:(id)arg1 didEndSendingToApplication:(id)arg2;
- (void)onAction;
- (void)OpenByApp;
- (void)openFile;
- (void)AddOpenByApp;
- (void)RemoveDownloadFail;
- (void)DownloadFile;
- (void)AddDownloadFail;
- (void)RemoveDownloadProgress;
- (void)SetProgress:(double)arg1 TotalSize:(double)arg2;
- (void)AddDownloadProgress;
- (void)viewWillLayoutSubviews;
- (void)initView;
- (void)initData;
- (void)didReceiveMemoryWarning;
- (void)viewDidLoad;
- (void)SafeDeleteDocument;
- (void)dealloc;
- (id)initWithRecordDataWrap:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

