//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class MultiImagePickerController, NSArray;

@protocol MultiImagePickerControllerDelegate <NSObject>

@optional
- (void)imagePickerControllerDidCancel:(MultiImagePickerController *)arg1;
- (void)imagePickerController:(MultiImagePickerController *)arg1 didFinishPickingImages:(NSArray *)arg2;
@end

