//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "WCDBCoding-Protocol.h"

@class NSData, NSString;

@interface MyWCTimeline : NSObject <WCDBCoding>
{
    unsigned int m_localId;
    unsigned int m_groupHint;
    NSString *m_id;
    NSString *m_fromUser;
    NSData *m_buffer;
    long long m___rowID;
}

+ (const basic_string_a490aa4c *)getWCDBPrimaryColumnName;
+ (const struct WCDBIndexHelper *)getWCDBIndexArray;
+ (unsigned long long)getWCDBIndexArrayCount;
+ (const map_490096f0 *)getFileValueTagIndexMap;
+ (id)getFileValueTypeTable;
+ (const map_490096f0 *)getPackedValueTagIndexMap;
+ (id)getPackedValueTypeTable;
+ (const map_64c9abee *)getValueNameIndexMap;
+ (id)getValueTable;
+ (id)dummyObject;
@property(nonatomic) long long __rowID; // @synthesize __rowID=m___rowID;
@property(retain, nonatomic) NSData *m_buffer; // @synthesize m_buffer;
@property(retain, nonatomic) NSString *m_fromUser; // @synthesize m_fromUser;
@property(retain, nonatomic) NSString *m_id; // @synthesize m_id;
@property(nonatomic) unsigned int m_groupHint; // @synthesize m_groupHint;
@property(nonatomic) unsigned int m_localId; // @synthesize m_localId;
- (void).cxx_destruct;
- (const map_490096f0 *)getValueTagIndexMap;
- (id)getValueTypeTable;
- (const WCDBCondition_91e67114 *)db_m_buffer;
- (const WCDBCondition_22fabacd *)db_m_fromUser;
- (const WCDBCondition_22fabacd *)db_m_id;
- (const WCDBCondition_c6db074e *)db_m_groupHint;
- (const WCDBCondition_c6db074e *)db_m_localId;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

