//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSArray.h>

@interface NSArray (NSArray_SafeJSON)
- (double)doubleAtIndex:(unsigned long long)arg1;
- (float)floatAtIndex:(unsigned long long)arg1;
- (long long)integerAtIndex:(unsigned long long)arg1;
- (id)dictionaryAtIndex:(unsigned long long)arg1;
- (id)arrayAtIndex:(unsigned long long)arg1;
- (id)stringAtIndex:(unsigned long long)arg1;
- (id)mm_safe_objectAtIndex:(long long)arg1;
@end

