//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface NSObject (ObjcRuntime)
- (void)removeAssociatedObjects;
- (void)detachObjectForKey:(id)arg1;
- (id)getAttachedObjectForKey:(id)arg1;
- (void)attachObject:(id)arg1 forKey:(id)arg2;
- (const void *)computeKeyFromString:(id)arg1;
@end

