//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSString.h>

@interface NSString (HTML)
- (id)stringByReplacingHTMLEntities;
- (id)stringByAddingHTMLEntities;
- (_Bool)hasSuffixCharacterFromSet:(id)arg1;
- (_Bool)hasPrefixCharacterFromSet:(id)arg1;
- (float)percentValue;
- (_Bool)isNumeric;
- (unsigned long long)integerValueFromHex;
@end

