//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface QBInfo : NSObject
{
}

+ (void)initialize;
+ (_Bool)isMediaATSON;
+ (_Bool)isATSON;
+ (void)initATSON;
+ (id)getDeviceIdSafety;
+ (id)getMacAddress;
+ (id)getMttVendorIdSafety;
+ (id)getLatestCachedUUID;
+ (id)getARandomUUID;
+ (long long)getWifiAddress;
+ (id)APPV;
+ (id)APPN;
+ (id)IDFV;
+ (id)IDFA;
+ (id)QUAForV23;

@end

