//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface QProxyManagerHelper : NSObject
{
}

+ (_Bool)isInDirectListWithRequest:(id)arg1;
+ (long long)commonDirectTypeWithRequest:(id)arg1 mainResource:(_Bool)arg2;
+ (int)subResourceTypeForRequest:(id)arg1;
+ (void)initialize;

@end

