//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMObject.h"

#import "PBCoding-Protocol.h"

@class NSString;

@interface QQOfflineServerTips : MMObject <PBCoding>
{
    unsigned int m_lastUpdateTime;
    NSString *m_displayMsg;
    NSString *m_qqScheme;
    NSString *m_downloadUrl;
}

+ (id)getSavePath;
+ (id)getSaveRootDir;
+ (id)loadFromCache;
+ (void)initialize;
@property(nonatomic) unsigned int m_lastUpdateTime; // @synthesize m_lastUpdateTime;
@property(retain, nonatomic) NSString *m_downloadUrl; // @synthesize m_downloadUrl;
@property(retain, nonatomic) NSString *m_qqScheme; // @synthesize m_qqScheme;
@property(retain, nonatomic) NSString *m_displayMsg; // @synthesize m_displayMsg;
- (void).cxx_destruct;
- (void)clearAndSave;
- (void)saveToCache;
- (const map_490096f0 *)getValueTagIndexMap;
- (id)getValueTypeTable;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

