//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface RFC3339DateTool : NSObject
{
}

+ (unsigned long long)UNIXTimestampFromString:(id)arg1;
+ (id)stringFromUNIXTimestamp:(unsigned long long)arg1;
+ (id)dateFromString:(id)arg1;
+ (id)stringFromDate:(id)arg1;
+ (void)initialize;

@end

