//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMObject.h"

@class NSDictionary, NSRecursiveLock;

@interface SafeDictionaryWrap : MMObject
{
    NSRecursiveLock *_lock;
    NSDictionary *_dic;
}

- (void).cxx_destruct;
- (unsigned long long)count;
- (id)valueForKey:(id)arg1;
- (void)safeSetDictionrary:(id)arg1;
- (id)init;

@end

