//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMUIView.h"

#import "PushSystemMsgViewDelegate-Protocol.h"

@class NSString, PushSystemMsgView, UIButton;
@protocol SetTrustedFriendTipsViewDelegate;

@interface SetTrustedFriendTipsView : MMUIView <PushSystemMsgViewDelegate>
{
    id <SetTrustedFriendTipsViewDelegate> _m_delegate;
    PushSystemMsgView *_tipsView;
    UIButton *_closeButton;
}

@property(retain, nonatomic) UIButton *closeButton; // @synthesize closeButton=_closeButton;
@property(retain, nonatomic) PushSystemMsgView *tipsView; // @synthesize tipsView=_tipsView;
@property(nonatomic) __weak id <SetTrustedFriendTipsViewDelegate> m_delegate; // @synthesize m_delegate=_m_delegate;
- (void).cxx_destruct;
- (id)genTipsMsg;
- (void)dismissSystemMsg;
- (void)layoutSubviews;
- (id)initWithDelegate:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

