//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "CommonMessageCellView.h"

@class ShareCardMessageViewModel, UILabel;

@interface ShareCardMessageCellView : CommonMessageCellView
{
    UILabel *m_nicknameLabel;
    UILabel *m_usernameLabel;
}

- (void).cxx_destruct;
- (void)onTouchUpInside;
- (void)onTouchDown;
- (id)operationMenuItems;
- (void)initUsernameLabel;
- (void)initNicknameLabel;
- (void)layoutContentView;
- (_Bool)canBeReused;

// Remaining properties
@property(readonly, nonatomic) ShareCardMessageViewModel *viewModel; // @dynamic viewModel;

@end

