//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMObject.h"

#import "PBCoding-Protocol.h"

@class NSString, UIImage;

@interface SightDraftItem : MMObject <PBCoding>
{
    int mode;
    NSString *thumbPath;
    NSString *videoPath;
    UIImage *_thumbImg;
    NSString *_moviePath;
}

+ (id)draftItemWithThumbImg:(id)arg1 andPath:(id)arg2 inMode:(int)arg3;
+ (void)initialize;
@property(retain, nonatomic) NSString *moviePath; // @synthesize moviePath=_moviePath;
@property(retain, nonatomic) UIImage *thumbImg; // @synthesize thumbImg=_thumbImg;
@property(retain, nonatomic) NSString *videoPath; // @synthesize videoPath;
@property(retain, nonatomic) NSString *thumbPath; // @synthesize thumbPath;
@property(nonatomic) int mode; // @synthesize mode;
- (void).cxx_destruct;
@property(readonly, nonatomic) unsigned int duration;
- (id)getVideoTmpPathAndCopyIfNeeded;
- (id)getThumbPath;
- (id)getVideoPath;
- (void)dealloc;
- (id)init;
- (const map_490096f0 *)getValueTagIndexMap;
- (id)getValueTypeTable;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

