//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMObject.h"

@class EmojiInfoObj;

@interface SingleEmotionDownloadWrap : MMObject
{
    _Bool _isTempFirst;
    EmojiInfoObj *_emojiInfoObj;
}

@property(nonatomic) _Bool isTempFirst; // @synthesize isTempFirst=_isTempFirst;
@property(retain, nonatomic) EmojiInfoObj *emojiInfoObj; // @synthesize emojiInfoObj=_emojiInfoObj;
- (void).cxx_destruct;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)arg1;
- (id)description;

@end

