//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCoding-Protocol.h"

@class NSString, UIColor;

@interface SystemMsgTextWrap : NSObject <NSCoding>
{
    NSString *text;
    struct CGPoint origin;
    unsigned int width;
    UIColor *color;
    unsigned int font;
}

@property(nonatomic) unsigned int font; // @synthesize font;
@property(retain, nonatomic) UIColor *color; // @synthesize color;
@property(nonatomic) unsigned int width; // @synthesize width;
@property(nonatomic) struct CGPoint origin; // @synthesize origin;
@property(retain, nonatomic) NSString *text; // @synthesize text;
- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;

@end

