//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class LineStyleWrap;

@interface TemplateDetailToplineWrap : NSObject
{
    LineStyleWrap *_keyWrap;
    LineStyleWrap *_valueWrap;
}

@property(retain, nonatomic) LineStyleWrap *valueWrap; // @synthesize valueWrap=_valueWrap;
@property(retain, nonatomic) LineStyleWrap *keyWrap; // @synthesize keyWrap=_keyWrap;
- (void).cxx_destruct;

@end

