//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMObject.h"

@interface TranslateSnsUtil : MMObject
{
}

+ (_Bool)isSameLanguage:(id)arg1;
+ (_Bool)IsIgnoreChar:(unsigned short)arg1;
+ (_Bool)IsEnChar:(unsigned short)arg1;
+ (_Bool)couldTranslateSns;
+ (_Bool)couldTranslateSnsComment:(id)arg1;
+ (_Bool)couldTranslateSnsContent:(id)arg1;
+ (_Bool)isTranslateSnsOff;
+ (id)getUserTranslateRootDir;

@end

