//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSMutableArray, NSString;

@interface WAAppTaskJumpWeAppInfo : NSObject
{
    unsigned int _debugMode;
    NSString *_appID;
    NSString *_originPreviousAppID;
    unsigned long long _jumpRole;
    unsigned long long _jumpToNextWeAppOperateScene;
    NSMutableArray *_arrChildWeApp;
    WAAppTaskJumpWeAppInfo *_parentWeApp;
    NSArray *_arrNativePage;
}

@property(retain, nonatomic) NSArray *arrNativePage; // @synthesize arrNativePage=_arrNativePage;
@property(nonatomic) __weak WAAppTaskJumpWeAppInfo *parentWeApp; // @synthesize parentWeApp=_parentWeApp;
@property(retain, nonatomic) NSMutableArray *arrChildWeApp; // @synthesize arrChildWeApp=_arrChildWeApp;
@property(nonatomic) unsigned long long jumpToNextWeAppOperateScene; // @synthesize jumpToNextWeAppOperateScene=_jumpToNextWeAppOperateScene;
@property(nonatomic) unsigned long long jumpRole; // @synthesize jumpRole=_jumpRole;
@property(nonatomic) unsigned int debugMode; // @synthesize debugMode=_debugMode;
@property(retain, nonatomic) NSString *originPreviousAppID; // @synthesize originPreviousAppID=_originPreviousAppID;
@property(retain, nonatomic) NSString *appID; // @synthesize appID=_appID;
- (void).cxx_destruct;
- (void)removeChildWeAppInList:(id)arg1;
- (void)removeAllChildWeApp;
- (id)getSiblingWeAppFromChildWeApp:(id)arg1;
- (id)getLastWeChatPluginChild;
- (id)getChildWeApp;
- (void)appendChildWeAppIfWeChatPlugin:(id)arg1;
- (id)getChildWeAppAppID;
- (id)getWeAppWebViewList;
- (id)description;
- (_Bool)isJumpToNextWeAppFromNativePage;
- (_Bool)isWebViewInNavigationController;
- (id)getWeAppWebViewAndNativePages;
- (void)dealloc;
- (id)init;

@end

