//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "IWAMsgNodeJSCoreCenterExt-Protocol.h"
#import "WACanvasViewDelegate-Protocol.h"

@class DotLoadingView, NSObject, NSString, UIImageView, WAAppCanvasWrapperViewData, WACanvasView;
@protocol OS_dispatch_queue;

@interface WAAppCanvasWrapperView : UIView <WACanvasViewDelegate, IWAMsgNodeJSCoreCenterExt>
{
    unsigned long long _beginTime;
    unsigned long long _firstDrawedTime;
    _Bool _isQueueSuspending;
    _Bool _isLoadingViewFading;
    unsigned int _coreId;
    NSObject<OS_dispatch_queue> *_drawQueue;
    WACanvasView *_canvasView;
    UIImageView *_logoImgView;
    UIView *_defaultLogoBgView;
    UIView *_loadingViewBgView;
    DotLoadingView *_loadingIndicator;
    unsigned long long _viewState;
    WAAppCanvasWrapperViewData *_viewData;
}

@property(retain, nonatomic) WAAppCanvasWrapperViewData *viewData; // @synthesize viewData=_viewData;
@property(nonatomic) unsigned long long viewState; // @synthesize viewState=_viewState;
@property(nonatomic) _Bool isLoadingViewFading; // @synthesize isLoadingViewFading=_isLoadingViewFading;
@property(retain, nonatomic) DotLoadingView *loadingIndicator; // @synthesize loadingIndicator=_loadingIndicator;
@property(retain, nonatomic) UIView *loadingViewBgView; // @synthesize loadingViewBgView=_loadingViewBgView;
@property(retain, nonatomic) UIView *defaultLogoBgView; // @synthesize defaultLogoBgView=_defaultLogoBgView;
@property(retain, nonatomic) UIImageView *logoImgView; // @synthesize logoImgView=_logoImgView;
@property(retain, nonatomic) WACanvasView *canvasView; // @synthesize canvasView=_canvasView;
@property(nonatomic) _Bool isQueueSuspending; // @synthesize isQueueSuspending=_isQueueSuspending;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *drawQueue; // @synthesize drawQueue=_drawQueue;
@property(readonly, nonatomic) unsigned int coreId; // @synthesize coreId=_coreId;
- (void).cxx_destruct;
- (void)hideDefaultLogoBgView;
- (void)hideLoadingView;
- (void)showDisabledView;
- (void)showDownloadFailView;
- (void)showLoadingView;
- (void)goDisabled;
- (void)goDrawed;
- (void)goDownloadFail;
- (void)goLoading;
- (void)onJSCore:(unsigned int)arg1 viewStateChanged:(unsigned long long)arg2;
- (void)onJSCore:(unsigned int)arg1 evaluatedResult:(id)arg2 reserve:(_Bool)arg3;
- (void)reportConsuming:(long long)arg1;
- (id)getImage:(id)arg1;
- (id)queryOfUrl:(id)arg1;
- (id)pathOfUrl:(id)arg1;
- (void)layoutSubviews;
- (void)resumeQueue;
- (void)suspendQueue;
- (void)onBecomeActive;
- (void)onResignActive;
- (void)resume;
- (void)pause;
- (void)start;
- (void)setupWithParams:(id)arg1;
- (void)initLogoView;
- (void)initLoadingView;
- (void)initCanvasView;
- (void)makeSureViewInited;
- (double)getMilliseconds:(struct timeval)arg1;
- (void)doReportDrawTime;
- (id)createTestSpeedReportItem;
- (id)createIDKeyReportItem;
- (void)releaseResourcesOnSubthread;
- (void)allocateResourcesOnSubthread;
- (void)dealloc;
- (void)initializeEnv;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

