//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMObject.h"

@class NSString;

@interface WAPageFlowSessionInfo : MMObject
{
    NSString *_sessionId;
    unsigned long long _scene;
    NSString *_sceneNote;
    unsigned long long _preScene;
    NSString *_preSceneNote;
    NSString *_referPageOfHomePage;
}

@property(copy, nonatomic) NSString *referPageOfHomePage; // @synthesize referPageOfHomePage=_referPageOfHomePage;
@property(copy, nonatomic) NSString *preSceneNote; // @synthesize preSceneNote=_preSceneNote;
@property(nonatomic) unsigned long long preScene; // @synthesize preScene=_preScene;
@property(copy, nonatomic) NSString *sceneNote; // @synthesize sceneNote=_sceneNote;
@property(nonatomic) unsigned long long scene; // @synthesize scene=_scene;
@property(copy, nonatomic) NSString *sessionId; // @synthesize sessionId=_sessionId;
- (void).cxx_destruct;
- (id)initWithSessionPrefix:(id)arg1;

@end

