//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WAReportBaseItem.h"

@class NSString;

@interface WAReportForwardMessageItem : WAReportBaseItem
{
    NSString *_currentTitle;
    NSString *_sharePath;
    NSString *_shareTitle;
    NSString *_shareId;
    long long _userCount;
    NSString *_userName;
}

@property(copy, nonatomic) NSString *userName; // @synthesize userName=_userName;
@property(nonatomic) long long userCount; // @synthesize userCount=_userCount;
@property(copy, nonatomic) NSString *shareId; // @synthesize shareId=_shareId;
@property(copy, nonatomic) NSString *shareTitle; // @synthesize shareTitle=_shareTitle;
@property(copy, nonatomic) NSString *sharePath; // @synthesize sharePath=_sharePath;
@property(copy, nonatomic) NSString *currentTitle; // @synthesize currentTitle=_currentTitle;
- (void).cxx_destruct;
- (id)reportString;

@end

