//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString, NSURLSession, NSURLSessionTask;
@protocol WARequestTaskDelegate;

@interface WARequestTask : NSObject
{
    NSString *_appID;
    NSURLSession *_urlSession;
    NSString *_taskID;
    NSURLSessionTask *_task;
    CDUnknownBlockType _completionHandler;
    _Bool _isRedirectInvalid;
    id <WARequestTaskDelegate> delegate;
}

@property __weak id <WARequestTaskDelegate> delegate; // @synthesize delegate;
- (void).cxx_destruct;
- (void)callCompletionHandlerWithError:(id)arg1 string:(id)arg2 statusCode:(long long)arg3 responseHeader:(id)arg4;
- (void)callCompletionHandlerWithString:(id)arg1 statusCode:(long long)arg2 responseHeader:(id)arg3;
- (void)callCompletionHandlerWithError:(id)arg1;
- (void)setCompletionHandler:(CDUnknownBlockType)arg1;
- (id)headerDictionaryFromResponse:(id)arg1;
- (void)markRedirectFail;
- (id)task;
- (void)cancelWithError:(id)arg1;
- (void)cancel;
- (void)startWithURL:(id)arg1 postData:(id)arg2 httpHeaders:(id)arg3 userAgent:(id)arg4 referer:(id)arg5 method:(id)arg6 completionHandler:(CDUnknownBlockType)arg7;
- (id)getTaskID;
- (void)dealloc;
- (id)initWithAppID:(id)arg1 urlSession:(id)arg2 taskID:(id)arg3;

@end

