//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WAReportBaseItem.h"

@class NSString;

@interface WAReportDestopShowItem : WAReportBaseItem
{
    unsigned long long _destopEnterScene;
    NSString *_appidList;
}

@property(copy, nonatomic) NSString *appidList; // @synthesize appidList=_appidList;
@property(nonatomic) unsigned long long destopEnterScene; // @synthesize destopEnterScene=_destopEnterScene;
- (void).cxx_destruct;
- (id)reportString;

@end

