//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMService.h"

#import "IMMNewSessionMgrExt-Protocol.h"
#import "IMsgExt-Protocol.h"
#import "ISessionInfoExt-Protocol.h"
#import "ISessionStorageDelegate-Protocol.h"
#import "MMService-Protocol.h"
#import "WAContactMgrExtension-Protocol.h"

@class MMBaseSessionStorage, NSString;

@interface WASessionMgr : MMService <ISessionStorageDelegate, IMMNewSessionMgrExt, ISessionInfoExt, IMsgExt, WAContactMgrExtension, MMService>
{
    MMBaseSessionStorage *_sessionStorage;
}

- (void).cxx_destruct;
- (void)onDeleteWeAppContact:(id)arg1;
- (void)onModifyWeAppContactList:(id)arg1;
- (void)OnUnReadCountChange:(id)arg1;
- (void)OnModMsg:(id)arg1 MsgWrap:(id)arg2;
- (void)OnDelMsg:(id)arg1;
- (void)OnAddMsgListForSession:(id)arg1 NotifyUsrName:(id)arg2;
- (long long)compareSession:(id)arg1 rightSession:(id)arg2;
- (id)importSessions;
- (void)onModifyDraft:(id)arg1 draft:(id)arg2 draftTime:(unsigned int)arg3;
- (void)onGetDraft:(id)arg1 draft:(id)arg2;
- (void)deleteMainFrameSession;
- (void)updateMainFrameSessionWithNotify:(_Bool)arg1;
- (id)genMainFrameSessionInfo;
- (void)onDeleteSessionOfUser:(id)arg1;
- (void)isUser:(id)arg1 hasSpecalSessionInfo:(id *)arg2;
- (void)isMessage:(id)arg1 Handled:(_Bool *)arg2;
- (void)isUser:(id)arg1 Handled:(_Bool *)arg2;
- (unsigned int)totalUnreadCount;
- (void)callExtOnSessionChange;
- (void)deleteSessionMessage:(id)arg1;
- (void)deleteAllSessions;
- (void)updateSessionAndNotifyUI:(id)arg1;
- (void)updateSessionForContactListChanged:(id)arg1;
- (unsigned int)updateSessionForUser:(id)arg1;
- (void)clearMainFrameSessionUnreadCount;
- (void)updateMainFrameSession;
- (void)deleteSessionAtIndex:(long long)arg1;
- (id)sessionInfoWithUsrName:(id)arg1;
- (id)sessionInfoAtIndex:(long long)arg1;
- (unsigned int)sessionCount;
- (void)setupData;
- (void)onServiceClearData;
- (void)onServiceReloadData;
- (void)onServiceInit;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

