//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <QuartzCore/CALayer.h>

#import "WAFloatObjectDelegate-Protocol.h"

@class CADisplayLink, NSMutableArray, NSMutableDictionary, NSString;

@interface WAVideoLayer : CALayer <WAFloatObjectDelegate>
{
    _Bool _playing;
    NSMutableDictionary *_floatList;
    NSMutableArray *_visibleList;
    CADisplayLink *_displayLink;
    double _currentTime;
    NSMutableArray *_unusedCells;
}

@property(retain, nonatomic) NSMutableArray *unusedCells; // @synthesize unusedCells=_unusedCells;
@property(nonatomic) double currentTime; // @synthesize currentTime=_currentTime;
@property(retain, nonatomic) CADisplayLink *displayLink; // @synthesize displayLink=_displayLink;
@property(retain, nonatomic) NSMutableArray *visibleList; // @synthesize visibleList=_visibleList;
@property(retain, nonatomic) NSMutableDictionary *floatList; // @synthesize floatList=_floatList;
@property(nonatomic) _Bool playing; // @synthesize playing=_playing;
- (void).cxx_destruct;
- (void)clearFloat;
- (void)onUpdateFloat;
- (void)forceUpdate;
- (void)updateVideoTime:(double)arg1;
- (void)drawInContext:(struct CGContext *)arg1;
- (void)addFloat:(id)arg1 color:(id)arg2;
- (double)generateSpeed:(double)arg1;
- (void)initFloat:(id)arg1;
- (void)setFrame:(struct CGRect)arg1;
- (void)onEnterScreen:(long long)arg1;
- (long long)getCurrentRow;
- (void)enableFloat:(_Bool)arg1;
- (void)invalidate;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

