//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WAWebViewPluginBase.h"

@class NSMutableArray, NSObject;
@protocol WAWebViewPlugin_ApiQueueProtocol;

@interface WAWebViewPlugin_APIQueue : WAWebViewPluginBase
{
    NSMutableArray *_arrEvent;
    struct NSObject *_runningEvent;
}

@property(retain) NSObject<WAWebViewPlugin_ApiQueueProtocol> *runningEvent; // @synthesize runningEvent=_runningEvent;
@property(retain) NSMutableArray *arrEvent; // @synthesize arrEvent=_arrEvent;
- (void).cxx_destruct;
- (void)removeApiEvent:(struct NSObject *)arg1;
- (void)checkApiEvent;
- (void)addApiEvent:(struct NSObject *)arg1 param:(id)arg2;
- (void)dealloc;
- (id)init;

@end

