//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSString, WAWebViewPluginScheduler, WxaExternalInfo;

@protocol WAWebViewJSLogicDelegate <NSObject>

@optional
- (WxaExternalInfo *)getWxaExternalInfo;
- (_Bool)isOpenDebugAndVConsole;
- (unsigned int)getDebugModeType;
- (unsigned long long)getAppVersion;
- (void)checkUserAuthWithJSAPI:(NSString *)arg1 handler:(void (^)(void))arg2 failHandler:(void (^)(NSString *))arg3;
- (_Bool)checkRunModeOnWebview:(NSString *)arg1;
- (_Bool)hasPermissionWithJSAPI:(NSString *)arg1 getState:(unsigned int *)arg2;
- (WAWebViewPluginScheduler *)getPluginScheduler;
- (NSString *)getCurrentAppId;
- (void)onInjectJSSuccess;
@end

