//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMService.h"

#import "MMService-Protocol.h"
#import "WAAppTaskMgrExt-Protocol.h"
#import "WAWebSocketHandlerDelegate-Protocol.h"

@class NSMutableDictionary, NSObject, NSString;
@protocol OS_dispatch_queue;

@interface WAWebSocketMgr : MMService <WAWebSocketHandlerDelegate, WAAppTaskMgrExt, MMService>
{
    NSMutableDictionary *_dicAppID2WebSocketHandler;
    NSObject<OS_dispatch_queue> *_workerQueue;
}

- (void).cxx_destruct;
- (void)webSocketDidClose:(id)arg1;
- (void)onAppTaskBackgroundNetworkInterruptedTimeout:(id)arg1;
- (void)onAppTaskTerminate:(id)arg1;
- (void)closeAndDeleteAllWebSocketHandler;
- (void)deleteHandler:(id)arg1;
- (void)interruptHandlerWithAppID:(id)arg1;
- (void)closeAndDeleteHandlerWithAppID:(id)arg1;
- (id)getHandlerWithAppID:(id)arg1;
- (id)getAndNewHandlerIfNotExistWithAppID:(id)arg1 appVersion:(unsigned long long)arg2 isNew:(_Bool *)arg3;
- (void)sendMessage:(id)arg1 isBuffer:(_Bool)arg2 withAppID:(id)arg3 completionHandler:(CDUnknownBlockType)arg4;
- (void)closeSocketWithAppID:(id)arg1 code:(long long)arg2 reason:(id)arg3;
- (void)connectSocketWithAppID:(id)arg1 appVersion:(unsigned long long)arg2 isIgnoreCheckDomain:(_Bool)arg3 url:(id)arg4 httpHeaders:(id)arg5 subProtocols:(id)arg6 completionHandler:(CDUnknownBlockType)arg7;
- (void)onServiceClearData;
- (void)onServiceReloadData;
- (void)onServiceInit;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

