//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WAWebViewPluginBase.h"

@class NSMutableArray;

@interface WAWebViewPlugin_EventQueue : WAWebViewPluginBase
{
    NSMutableArray *_arrDidAppearHandler;
}

- (void).cxx_destruct;
- (_Bool)handleEvent:(unsigned long long)arg1 userInfo:(id)arg2;
- (void)onWebViewDidAppear;
- (void)addDidAppearHandler:(CDUnknownBlockType)arg1;
- (void)dealloc;
- (id)init;

@end

