//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WCAccountBaseControlLogic.h"

#import "WCAccountManualAuthControlLogicDelegate-Protocol.h"
#import "WCAccountNewPhoneVerifyViewControllerDelegate-Protocol.h"
#import "WCAccountSetPasswordViewControllerDelegate-Protocol.h"
#import "WCAccountVerifyCodeHandlerDelegate-Protocol.h"

@class NSString, PhoneNumberFormatLogic, WCAccountManualAuthControlLogic, WCAccountNewPhoneVerifyViewController, WCAccountVerifyCodeHandler;

@interface WCAccountNewPhoneLoginControlLogic : WCAccountBaseControlLogic <WCAccountNewPhoneVerifyViewControllerDelegate, WCAccountManualAuthControlLogicDelegate, WCAccountSetPasswordViewControllerDelegate, WCAccountVerifyCodeHandlerDelegate>
{
    WCAccountVerifyCodeHandler *_verifyCodeHandler;
    WCAccountManualAuthControlLogic *_manualAuthLogic;
    _Bool _bNeedSetPwd;
    PhoneNumberFormatLogic *_phoneNumFormatter;
    WCAccountNewPhoneVerifyViewController *_currentVC;
}

- (void).cxx_destruct;
- (void)onSetPasswordOK;
- (void)onSetPasswordBack;
- (_Bool)onManualAuthControlLogicError:(id)arg1;
- (void)checkHavePwd;
- (void)onManualAuthControlLogicStop:(unsigned long long)arg1 response:(id)arg2;
- (void)onGoToSecurityCenter:(unsigned int)arg1;
- (void)onNewPhoneVerifyProblem;
- (void)onNewPhoneVerifyGotoSecurityCenter;
- (void)onNewPhoneVerifyNextWithPwd:(id)arg1;
- (void)onNewPhoneVerifyNextWithVerifyCode:(id)arg1;
- (void)onNewPhoneVerifyFirstTime:(_Bool)arg1;
- (void)onNewPhoneVerifyBack;
- (void)onHandlerCheckLoginVerifyCode:(id)arg1 ticket:(id)arg2 controlShowFlag:(unsigned int)arg3 userName:(id)arg4 password:(id)arg5 StyleKeyValue:(id)arg6;
- (void)onHandlerGetVerifyCodeSuccessWithStyleKeyValue:(id)arg1;
- (void)loginForPhone;
- (void)jumpToManulLoginControlMgrToRegister:(id)arg1;
- (void)login_but_registerForPhone;
- (void)loginAccount;
- (void)startLogic;
- (id)initWithData:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

