//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WCAccountBaseViewController.h"

#import "IMMLanguageMgrExt-Protocol.h"
#import "WCActionSheetDelegate-Protocol.h"

@class NSArray, NSMutableArray, NSString, UIButton, UILabel, UIView, WCAccountTextFieldItem, WCBaseKeyboardToolBar;
@protocol WCAccountLoginLastUserViewControllerDelegate;

@interface WCAccountLoginLastUserViewController : WCAccountBaseViewController <IMMLanguageMgrExt, WCActionSheetDelegate>
{
    WCBaseKeyboardToolBar *m_keyboardBar;
    UILabel *m_labelUserName;
    UILabel *m_labelPhoneNumber;
    UIView *m_passwordView;
    UIView *m_passwordNeedAnimationView;
    WCAccountTextFieldItem *m_textFieldPwdItem;
    UIView *m_passwordSeparatorLine;
    UIButton *m_passwordSwitchAccountBtn;
    UIButton *m_passwordLoginBtn;
    UIView *m_verifyCodeView;
    UIView *m_verifyCodeNeedAnimationView;
    WCAccountTextFieldItem *m_textFieldVerifyCodeItem;
    UIButton *m_resendCodeBtn;
    UIView *m_verifyCodeSeparatorLine;
    UIButton *m_verifyCodeSwitchAccountBtn;
    UIButton *m_verifyCodeLoginBtn;
    UIView *m_voicePrintView;
    UIButton *m_voicePrintLoginBtn;
    UIButton *m_voiceSwitchAccountBtn;
    id <WCAccountLoginLastUserViewControllerDelegate> m_delegate;
    NSString *m_nsName;
    long long m_iCountDown;
    _Bool m_bFirstLoop;
    NSMutableArray *m_availableLoginTypeArr;
    long long m_currentLoginType;
    NSArray *m_accountChangeLoginTypeWording;
    _Bool m_bInAnimation;
    long long _m_iCount;
}

@property(nonatomic) long long m_iCount; // @synthesize m_iCount=_m_iCount;
- (void).cxx_destruct;
- (_Bool)useGrayBackgroundColor;
- (void)actionSheet:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)WCBaseInfoItemEditChanged:(id)arg1;
- (void)setDelegate:(id)arg1;
- (void)didReceiveMemoryWarning;
- (void)vcResignFirstResponder;
- (void)onSwitchPwdInput;
- (void)onResendClicked;
- (void)switchEaseInOutToType:(long long)arg1;
- (void)onSwitch;
- (void)onBothDeviceClicked;
- (void)onNext;
- (void)updateSendVerifyCodeButton;
- (void)startTimer;
- (void)viewDidLoad;
- (void)adjustTableViewRect;
- (void)adjustViewAndNavBarRect;
- (double)getVisibleHeight;
- (void)hideKeyBoard;
- (void)onLastUserChangeAccountForIPad:(id)arg1;
- (id)createHeadImgView;
- (id)createVoicePrintLoginBtn;
- (id)createPwdInputView:(id)arg1;
- (void)initVerifyCodeView;
- (void)initPasswordView;
- (void)initVoicePrintView;
- (id)getSwitchBtnTitleWithCurrentLoginType:(unsigned long long)arg1;
- (void)initFooterView;
- (void)initHeaderView;
- (void)initNavigationBar;
- (void)initData;
- (void)onMore:(id)arg1;
- (void)onLastUserVoicePrintLogin;
- (id)getDisplayPhoneNumber;
- (id)getDisplayLoginName;
- (_Bool)isLastQQLogin;
- (_Bool)isLastLoginAcountTypePhone;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

