//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WCAccountBaseViewController.h"

#import "CountryCodePickerDelegate-Protocol.h"
#import "ILinkEventExt-Protocol.h"
#import "UITextFieldDelegate-Protocol.h"
#import "WCActionSheetDelegate-Protocol.h"

@class CountryCodeWrap, NSString, PhoneNumberFormatLogic, UIButton, UIView, WCAccountTextFieldItem, WCActionSheet, WCBaseKeyboardToolBar;
@protocol WCAccountMainLoginViewControllerDelegate;

@interface WCAccountMainLoginViewController : WCAccountBaseViewController <WCActionSheetDelegate, CountryCodePickerDelegate, UITextFieldDelegate, ILinkEventExt>
{
    id <WCAccountMainLoginViewControllerDelegate> _delegate;
    UIView *_phoneHeaderView;
    WCAccountTextFieldItem *_textFieldCountryCodeSelectItem;
    WCAccountTextFieldItem *_textFieldCountryCodeItem;
    WCAccountTextFieldItem *_textFieldPhoneNumberItem;
    PhoneNumberFormatLogic *_phoneNumFormatter;
    CountryCodeWrap *_curCountryCode;
    UIView *_userHeaderView;
    WCAccountTextFieldItem *_textFieldUserNameItem;
    WCAccountTextFieldItem *_textFieldUserPwdItem;
    WCBaseKeyboardToolBar *_keyboardBar;
    UIButton *_btnNext;
    unsigned long long _enLoginType;
    _Bool _bInSwitchAnimation;
    WCActionSheet *_actionSheet;
    _Bool _bShouldShowBackBtn;
    _Bool _bShowPhoneLoginViewFirst;
}

@property(nonatomic) _Bool bShowPhoneLoginViewFirst; // @synthesize bShowPhoneLoginViewFirst=_bShowPhoneLoginViewFirst;
@property(nonatomic) _Bool bShouldShowBackBtn; // @synthesize bShouldShowBackBtn=_bShouldShowBackBtn;
- (void).cxx_destruct;
- (_Bool)useGrayBackgroundColor;
- (void)didReceiveMemoryWarning;
- (void)WCBaseInfoItemPressReturnKey:(id)arg1;
- (void)findCountryCode;
- (void)WCBaseInfoItemEditChanged:(id)arg1;
- (void)CountryCodePickerDidPickCountryCode:(id)arg1;
- (void)actionSheet:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)userDidClickMore;
- (void)userDidClickBack;
- (void)vcResignFirstResponder;
- (void)switchToPhoneLogin;
- (void)switchToUserLogin;
- (void)onSwitch;
- (void)onBothDeviceClicked;
- (void)onNext;
- (void)showCountryCode;
- (void)checkNextBtnEnable;
- (void)showFooterViewWithSwitchBtnTitle:(id)arg1 loginBtnTitle:(id)arg2;
- (void)showUserLoginFooter;
- (void)showPhoneLoginFooter;
- (void)showCountryCodePickerView;
- (void)initTableView;
- (void)viewDidLoad;
- (void)setupWithData:(id)arg1;
- (void)setDelegate:(id)arg1;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

