//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface WCAddressAuthenticationSturct : NSObject
{
    NSString *m_nsHandleUrl;
    NSString *m_appID;
    int m_uiPayRcptScene;
}

@property(nonatomic) int m_uiPayRcptScene; // @synthesize m_uiPayRcptScene;
@property(retain, nonatomic) NSString *m_nsHandleUrl; // @synthesize m_nsHandleUrl;
@property(retain, nonatomic) NSString *m_appID; // @synthesize m_appID;
- (void).cxx_destruct;
- (void)dealloc;

@end

