//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableArray, WCBGAuthor;

@interface WCBGAlbum : NSObject
{
    WCBGAuthor *author;
    NSMutableArray *groupList;
}

@property(retain, nonatomic) NSMutableArray *groupList; // @synthesize groupList;
@property(retain, nonatomic) WCBGAuthor *author; // @synthesize author;
- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;

@end

