//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WCBaseControlLogic.h"

@class WCBizLoadingView;

@interface WCBizControlLogic : WCBaseControlLogic
{
    WCBizLoadingView *m_loadView;
}

- (void).cxx_destruct;
- (void)startCommonLoadingWithTips:(id)arg1;
- (void)stopCommonLoading;
- (void)startCommonLoading;
- (void)startLoadingOnMainWindow;
- (void)stopLoadingOnMainWindow;
- (void)showLoadingOK:(id)arg1;
- (void)stopLoading;
- (void)startLoadingWithTip:(id)arg1;
- (void)startLoadingBlocked;
- (void)startLoading;
- (void)dealloc;
- (void)initLoadView;

@end

