//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMObject.h"

@class NSString;

@interface WCCardTpInfoItem : MMObject
{
    NSString *_cardTpID;
    NSString *_cardCode;
}

@property(retain, nonatomic) NSString *cardCode; // @synthesize cardCode=_cardCode;
@property(retain, nonatomic) NSString *cardTpID; // @synthesize cardTpID=_cardTpID;
- (void).cxx_destruct;
- (void)dealloc;

@end

