//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMObject.h"

#import "NSCoding-Protocol.h"

@class NSString;

@interface WCCanvasComponentSightVideoInfo : MMObject <NSCoding>
{
    _Bool _allowVoice;
    int _displayType;
    NSString *_sightVideoUrl;
    NSString *_sightThumbUrl;
    double _sightDisplayWidth;
    double _sightDisplayHeight;
}

@property(nonatomic) _Bool allowVoice; // @synthesize allowVoice=_allowVoice;
@property(nonatomic) double sightDisplayHeight; // @synthesize sightDisplayHeight=_sightDisplayHeight;
@property(nonatomic) double sightDisplayWidth; // @synthesize sightDisplayWidth=_sightDisplayWidth;
@property(nonatomic) int displayType; // @synthesize displayType=_displayType;
@property(retain, nonatomic) NSString *sightThumbUrl; // @synthesize sightThumbUrl=_sightThumbUrl;
@property(retain, nonatomic) NSString *sightVideoUrl; // @synthesize sightVideoUrl=_sightVideoUrl;
- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)init;

@end

