//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMObject.h"

@class WCCardTipItem;

@interface WCCardTipController : MMObject
{
    WCCardTipItem *_wcCardTip;
}

- (void).cxx_destruct;
- (void)saveWCCardTipStg;
- (id)GetPathOfWCCardTipStorage;
- (id)getCardTip;
- (void)clearWCCardTip;
- (void)setWCCardTip:(id)arg1;
- (void)loadTipStg;
- (id)init;

@end

