//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMObject.h"

#import "NSCoding-Protocol.h"

@class NSArray;

@interface WCCanvsComponentScrollGroupListInfo : MMObject <NSCoding>
{
    int _pageCtrType;
    int _isFullScreen;
    NSArray *_componentGroupList;
}

@property(nonatomic) int isFullScreen; // @synthesize isFullScreen=_isFullScreen;
@property(nonatomic) int pageCtrType; // @synthesize pageCtrType=_pageCtrType;
@property(retain, nonatomic) NSArray *componentGroupList; // @synthesize componentGroupList=_componentGroupList;
- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)init;

@end

