//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMObject.h"

#import "NSCoding-Protocol.h"

@class NSString, WCCanvasComponentScrollGroupInfo;

@interface WCCanvasComponentNewScrollInfo : MMObject <NSCoding>
{
    WCCanvasComponentScrollGroupInfo *_componentGroupList;
    NSString *_bgColorTheme;
    double _bgColorAlpha;
}

@property(nonatomic) double bgColorAlpha; // @synthesize bgColorAlpha=_bgColorAlpha;
@property(retain, nonatomic) NSString *bgColorTheme; // @synthesize bgColorTheme=_bgColorTheme;
@property(retain, nonatomic) WCCanvasComponentScrollGroupInfo *componentGroupList; // @synthesize componentGroupList=_componentGroupList;
- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)init;

@end

