//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WCBaseTextViewItem.h"

@class UIButton;

@interface WCClearModeTextViewItem : WCBaseTextViewItem
{
    UIButton *m_clearButton;
}

- (void).cxx_destruct;
- (void)setClearButtonHidden:(_Bool)arg1;
- (void)OnClear:(id)arg1;
- (void)initView:(struct CGRect)arg1;
- (id)scaleImage:(id)arg1 toSize:(struct CGSize)arg2;

@end

