//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSString;

@protocol WCDataBaseEventDelegate <NSObject>

@optional
- (_Bool)onDatabaseCorrupt:(NSString *)arg1 errorCode:(int)arg2 opType:(unsigned int)arg3;
- (void)onGenerateNewHandle:(struct sqlite3 *)arg1;
- (void)onTransactionRollback;
@end

