//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface WCDBConfigWalFrame : NSObject
{
    _Bool m_check;
    _Bool m_prevent;
}

+ (void)initialize;
@property(nonatomic) _Bool m_prevent; // @synthesize m_prevent;
@property(nonatomic) _Bool m_check; // @synthesize m_check;
- (const map_490096f0 *)getValueTagIndexMap;
- (id)getValueTypeTable;

@end

