//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface WCDBConfigResultCache : NSObject
{
    _Bool m_stop;
}

+ (void)initialize;
@property(nonatomic) _Bool m_stop; // @synthesize m_stop;
- (const map_490096f0 *)getValueTagIndexMap;
- (id)getValueTypeTable;

@end

