//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface WCDBErrorReport : NSObject
{
}

+ (void)ReportWithDatabaseID:(unsigned int)arg1 operationID:(unsigned int)arg2 errorCode:(unsigned int)arg3 extendedError:(unsigned int)arg4;
+ (unsigned long long)getDeviceLazyFreeSpace;
+ (_Bool)isLazyFreeSpaceLow;
+ (void)checkLazyFreeSpace;

@end

