//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMObject.h"

@class NSData, WCDevice;

@interface WCDeviceScanExt : MMObject
{
    WCDevice *_device;
    NSData *_extData;
    unsigned int _lastOnScanTime;
}

@property(nonatomic) unsigned int lastOnScanTime; // @synthesize lastOnScanTime=_lastOnScanTime;
@property(retain, nonatomic) NSData *extData; // @synthesize extData=_extData;
@property(retain, nonatomic) WCDevice *device; // @synthesize device=_device;
- (void).cxx_destruct;
- (void)dealloc;

@end

