//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMObject.h"

#import "WCDBCoding-Protocol.h"

@class NSString;

@interface WCDurationLogItem : MMObject <WCDBCoding>
{
    unsigned int localId;
    unsigned int activeStartTime;
    unsigned int activeEndTime;
    long long m___rowID;
}

+ (id)stringFromItems:(id)arg1;
+ (id)logItem;
+ (const basic_string_a490aa4c *)getWCDBPrimaryColumnName;
+ (const struct WCDBIndexHelper *)getWCDBIndexArray;
+ (unsigned long long)getWCDBIndexArrayCount;
+ (const map_490096f0 *)getFileValueTagIndexMap;
+ (id)getFileValueTypeTable;
+ (const map_490096f0 *)getPackedValueTagIndexMap;
+ (id)getPackedValueTypeTable;
+ (const map_64c9abee *)getValueNameIndexMap;
+ (id)getValueTable;
+ (id)dummyObject;
@property(nonatomic) long long __rowID; // @synthesize __rowID=m___rowID;
@property(nonatomic) unsigned int activeEndTime; // @synthesize activeEndTime;
@property(nonatomic) unsigned int activeStartTime; // @synthesize activeStartTime;
@property(nonatomic) unsigned int localId; // @synthesize localId;
@property(readonly, copy) NSString *description;
- (void)reset;
- (const map_490096f0 *)getValueTagIndexMap;
- (id)getValueTypeTable;
- (const WCDBCondition_c6db074e *)db_activeEndTime;
- (const WCDBCondition_c6db074e *)db_activeStartTime;
- (const WCDBCondition_c6db074e *)db_localId;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

