//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class MMUIViewController, UIViewController, WCDataItem, WCMediaItem;

@protocol WCImageFullScreenViewContainerDelegateForHBV4 <NSObject>
- (void)onGreetingTipBtnClicked;
- (void)onAnimateFadeOut;
- (void)onPushViewController:(UIViewController *)arg1 animated:(_Bool)arg2;
- (MMUIViewController *)onGetViewController;
- (void)onExposeWithDataItem:(WCDataItem *)arg1;
- (void)onLongPressedWithMediaItem:(WCMediaItem *)arg1;
- (void)onContainerAnimationHideStop;
- (void)onContainerAnimationHideStart;
- (void)onContainerAnimationShowStop;
- (void)onContainerAnimationShowStart;
- (void)animationHideWithRotate;
@end

