//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface WCLabsStorage : NSObject
{
}

+ (id)loadClearedRedDotLabsAppidAryInAppEntracnce;
+ (_Bool)saveClearedRedDotLabsAppidAryInAppEntracnce:(id)arg1;
+ (id)getClearedRedDotLabsAppidAryPathInAppEntracnce;
+ (id)loadClearedRedDotLabsAppidAry;
+ (_Bool)saveClearedRedDotLabsAppidAry:(id)arg1;
+ (id)getClearedRedDotLabsAppidAryPath;
+ (id)loadLabsCommonInfo;
+ (_Bool)saveLabsCommonInfo:(id)arg1;
+ (id)getLabsCommonInfoPath;
+ (id)loadLabsAppItemDic;
+ (_Bool)saveLabsAppItemDic:(id)arg1;
+ (id)getLabsAppItemDicPath;

@end

