//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@class MMBadgeView, MMUILabel, MMWebImageView, UIView;

@interface WCLabsSettingCell : UITableViewCell
{
    MMUILabel *_titleLabel;
    MMUILabel *_descLabel;
    MMWebImageView *_thumbImageView;
    UIView *_backgroundView;
    MMBadgeView *_badgeView;
}

+ (double)heightForLabsItem:(id)arg1;
- (void).cxx_destruct;
- (void)initBadgeView;
- (void)initThumbImageView;
- (void)initDescLabel;
- (void)initTitleLabel;
- (void)initBackgroundView;
- (void)configureWithLabsItem:(id)arg1;
- (void)layoutSubviews;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

