//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMObject.h"

@interface WCNewClickStatUtility : MMObject
{
}

+ (id)getWidgetRecordDataFileByPageID:(id)arg1 andTimeStamp:(unsigned int)arg2;
+ (id)getWidgetRecordDataDir;
+ (unsigned int)calCostTimeFrom:(struct timeval)arg1;
+ (unsigned int)getNewContexID:(unsigned int)arg1;
+ (id)shortenPageID:(id)arg1;
+ (id)getPageStatDataCheckFilePath;
+ (void)unCompressSrcDataWithLen:(id)arg1 dest:(id)arg2 length:(long long)arg3;
+ (unsigned int)UinHash:(unsigned int)arg1;
+ (id)getReportConfigFilePath;
+ (id)getPageStatisticDataFilePath;
+ (id)getAppStatisticDataFilePath;
+ (id)getUsrReportDataDir;
+ (id)getReportDataDir;

@end

