//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class CgiF2FRcvVoiceResp, NSDictionary, NSString;

@protocol WCPayF2FVoiceCgiDelegate <NSObject>
- (void)OnGetWCPayF2FVoiceRespErrorWithPayload:(NSDictionary *)arg1 billNo:(NSString *)arg2;
- (void)OnGetWCPayF2FVoiceRespOK:(CgiF2FRcvVoiceResp *)arg1 payload:(NSDictionary *)arg2 billNo:(NSString *)arg3;
@end

