//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WCPayBaseViewController.h"

#import "WCPayTransferMoneyPaidSuccessViewV2Delegate-Protocol.h"

@class NSString, WCPayTransferMoneyPaidSuccessViewV2;
@protocol WCPayTranferMoneyPaidSuccessViewControllerDelegate;

@interface WCPayTranferMoneyPaidSuccessViewController : WCPayBaseViewController <WCPayTransferMoneyPaidSuccessViewV2Delegate>
{
    _Bool m_bNeedBindCard;
    id <WCPayTranferMoneyPaidSuccessViewControllerDelegate> m_delegate;
    WCPayTransferMoneyPaidSuccessViewV2 *_m_layoutV2;
}

@property(retain, nonatomic) WCPayTransferMoneyPaidSuccessViewV2 *m_layoutV2; // @synthesize m_layoutV2=_m_layoutV2;
- (void).cxx_destruct;
- (void)onWCPayTransferMoneyPaidSuccessViewV2ClickDone;
- (void)didReceiveMemoryWarning;
- (void)viewWillBeDismissed:(_Bool)arg1;
- (void)viewWillBePoped:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)refreshViewWithData:(id)arg1;
- (void)onSubscribeAppBtn:(id)arg1;
- (void)reloadTableView;
- (void)layoutV2;
- (void)selectNeedBindCard:(id)arg1;
- (void)initNavigationBar;
- (void)OnHistoryOrderDetailBack;
- (void)setDelegate:(id)arg1;
- (id)init;
- (_Bool)useBlackStatusbar;
- (_Bool)useTransparentNavibar;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

