//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WCPayControlLogic.h"

#import "WCBaseControlMgrExt-Protocol.h"

@class JSEvent, NSString, WCPayF2FJSApiAuthenticationControlLogic, WCPayF2FReceiveDetailControlLogic, WCPayJSApiAuthenticationControlLogic;

@interface WCPayJSApiOpenWCPayViewControl : WCPayControlLogic <WCBaseControlMgrExt>
{
    JSEvent *m_jsEvent;
    WCPayJSApiAuthenticationControlLogic *m_oAuthenticationLogic;
    int m_enWCPayCheckAuthorityScene;
    int m_enWCPayCheckOpenWCPayViewAuthorityScene;
    WCPayF2FJSApiAuthenticationControlLogic *_f2fJSApiAuthenControlLogic;
    WCPayF2FReceiveDetailControlLogic *_f2fDetailControlLogic;
}

@property(retain, nonatomic) WCPayF2FReceiveDetailControlLogic *f2fDetailControlLogic; // @synthesize f2fDetailControlLogic=_f2fDetailControlLogic;
@property(retain, nonatomic) WCPayF2FJSApiAuthenticationControlLogic *f2fJSApiAuthenControlLogic; // @synthesize f2fJSApiAuthenControlLogic=_f2fJSApiAuthenControlLogic;
- (void).cxx_destruct;
- (void)onWCBaseLogicDidStop:(unsigned int)arg1;
- (void)stopLogic;
- (void)dealloc;
- (void)startLogic;
- (id)initWithJSEvent:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

