//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WCPayBaseViewController.h"

#import "ILinkEventExt-Protocol.h"
#import "MMWebViewDelegate-Protocol.h"
#import "WCPayLogicMgrExt-Protocol.h"
#import "WCPayNoticeBannerDelegate-Protocol.h"

@class NSDictionary, NSMutableArray, NSString, UIButton;

@interface WCPayCardListViewController : WCPayBaseViewController <WCPayNoticeBannerDelegate, WCPayLogicMgrExt, ILinkEventExt, MMWebViewDelegate>
{
    NSMutableArray *m_arrPayCardDetailView;
    unsigned int totalHeight;
    UIButton *qaButton;
    NSDictionary *m_dicBanners;
}

- (void).cxx_destruct;
- (id)getNoticeBanner;
- (void)banner:(id)arg1 clickWithUrl:(id)arg2;
- (void)onQAButtonClick;
- (void)webViewReturn:(id)arg1;
- (void)gotoLoanMoney;
- (void)didReceiveMemoryWarning;
- (void)onClickCard:(id)arg1;
- (void)onClickBalanceView:(id)arg1;
- (void)onClickWXBorrowMoneyItemView:(id)arg1;
- (void)onClickWXBorrowMoneyItem:(id)arg1;
- (void)onClickVirtualCardAndChecking:(id)arg1;
- (void)onClickVirtualCard:(id)arg1;
- (void)refreshViewWithData:(id)arg1;
- (void)didShowAddCard;
- (void)showOfflinePay;
- (void)makeLoanMoneyCell:(id)arg1;
- (void)makeAddCardCell:(id)arg1;
- (void)makeVirtualCardCell:(id)arg1 cellInfo:(id)arg2;
- (void)makeWXBorrowMoneyItemCell:(id)arg1 cellInfo:(id)arg2;
- (void)makeBaseExtentionCell:(id)arg1;
- (void)viewWillBePoped:(_Bool)arg1;
- (void)reloadNavigationItem;
- (void)viewDidLoad;
- (void)viewDidLayoutSubviews;
- (void)initView;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

