//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMUIViewController.h"

#import "MMWebSearchViewDelegate-Protocol.h"
#import "SGTopEntryViewDelegate-Protocol.h"
#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"
#import "UITextFieldDelegate-Protocol.h"
#import "WSSuggestionTableViewCellDelegate-Protocol.h"
#import "WSTagSearchDelegate-Protocol.h"
#import "scrollViewDelegate-Protocol.h"
#import "tableViewDelegate-Protocol.h"

@class MMScrollView, MMTableView, MMTagTextField, MMTitleView, MMUILabel, MMWebSearchController, NSMutableArray, NSString, SGTopEntryView, UIButton, UIImageView, UIView, WSLabelIconButton, WSTagSearchLogic;

@interface WCWebSearchViewController : MMUIViewController <UITextFieldDelegate, UITableViewDelegate, UITableViewDataSource, tableViewDelegate, scrollViewDelegate, SGTopEntryViewDelegate, MMWebSearchViewDelegate, WSTagSearchDelegate, WSSuggestionTableViewCellDelegate>
{
    NSString *_lastFormatQueryFromMultiStageForFixingWKSearchBug;
    UIView *_navBarBkg;
    UIView *_navBarShadowView;
    UIView *_navBarSwitchContentBackView;
    UIView *_navBarSwitchContentView;
    SGTopEntryView *_navBarSwitchPanel;
    UIButton *_navBarSwitchAllButton;
    unsigned long long _currentSwitchBusinessType;
    MMTitleView *_titleView;
    UIView *_navContentView;
    UIView *_navContentRightDivideView;
    WSLabelIconButton *_navSwitchButton;
    MMTagTextField *_navSearchTextField;
    UIImageView *_navSearchLeftView;
    MMUILabel *_navTitleLabel;
    UIView *_animationSwitchView;
    MMScrollView *_scrollableView;
    UIView *_contentView;
    UIView *_blurView;
    UIView *_cornerWrapView;
    UIView *_cornerClipView;
    UIView *_contentSearchTextFieldWrapView;
    MMTagTextField *_contentSearchTextField;
    UIImageView *_contentSearchLeftView;
    MMTableView *_suggestionTableView;
    UIView *_keyboardToolBanner;
    UIButton *_keyboardCancelButton;
    UIView *_dynamicContentWrapView;
    SGTopEntryView *_guideEntryView;
    MMWebSearchController *_webSearchController;
    WSTagSearchLogic *_tagSearchLogic;
    NSMutableArray *_arrSugData;
    _Bool _isAnimatingToWebSearch;
    int _sugOpStat;
    _Bool _vertSearchMayHasData;
}

- (void).cxx_destruct;
- (void)onTagSearchBarInfoChangedToNotify:(id)arg1;
- (void)onPreSearch:(id)arg1 bizType:(unsigned long long)arg2;
- (void)onSearchBackToPreviousView;
- (void)onSearchLaunchNextViewWithBizType:(unsigned long long)arg1;
- (void)onUpdateNativeSuggestion;
- (void)onSearchReset;
- (void)onSearchInputSetPlaceHolder:(id)arg1;
- (void)onSearchInputSetText:(id)arg1 tagInfo:(id)arg2;
- (double)webSearchViewPosY;
- (void)startCommonSearch:(id)arg1 withSugId:(id)arg2;
- (void)startVerticalWebSearch:(unsigned long long)arg1;
- (void)updateNavBarSwitchAllButtonColorWithText:(id)arg1;
- (void)setSwitchButtonText:(id)arg1;
- (void)onClickWithData:(id)arg1;
- (void)removeHistorySuggestion:(id)arg1;
- (id)baseNativeSugReportParams;
- (void)setSuggestionModel:(id)arg1;
- (void)onClickSuggestionRightButton:(id)arg1;
- (void)touchesMoved_TableView:(id)arg1 withEvent:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (void)touchesBegan_ScrollView:(id)arg1 withEvent:(id)arg2;
- (_Bool)textFieldShouldReturn:(id)arg1;
- (_Bool)textFieldShouldClear:(id)arg1;
- (void)onTextFieldChanged:(id)arg1;
- (_Bool)textField:(id)arg1 shouldChangeCharactersInRange:(struct _NSRange)arg2 replacementString:(id)arg3;
- (void)textFieldDidEndEditing:(id)arg1;
- (void)textFieldDidBeginEditing:(id)arg1;
- (_Bool)isDetailSearch;
- (_Bool)isVertSearh;
- (_Bool)isMixSearch;
- (id)getSearchMarkImageForBusinesstype:(unsigned long long)arg1;
- (id)getPlaceHolderForBusinessType:(unsigned long long)arg1;
- (id)getMixSearchPlaceHolder;
- (void)setContentSearchUIForType:(unsigned long long)arg1;
- (void)resetContentSearch;
- (void)resetFromWebSearch;
- (void)resetTableView;
- (void)registerTagSearchLogic;
- (void)removeBlurEffect;
- (void)addBlurEffect;
- (void)animateDisplayContentViewWithDuration:(double)arg1;
- (void)endWebSearchAnimation;
- (void)beginWebSearchAnimation;
- (void)didEndWebSearch;
- (void)willEndWebSearch;
- (void)didBeginWebSearch;
- (void)willBeginWebSearch;
- (void)setPlaceImage:(id)arg1;
- (void)adjustContentTopMargin:(double)arg1;
- (void)setNavLeftBarItemHidden:(_Bool)arg1;
- (void)forceSetSwitchButtonHidden:(_Bool)arg1;
- (void)layoutSwitchButton;
- (void)layoutNavContentWithBizType:(unsigned long long)arg1;
- (void)layoutNavContentForNormalStatus;
- (void)layoutNavContentForEditStatus;
- (void)layoutContent;
- (void)layoutNavBarSwitchContent;
- (void)onTapNavSwitchContentBackView:(id)arg1;
- (void)onSwitchSearchTypeForDefault:(id)arg1;
- (_Bool)isDisplayingSwitchPanel;
- (void)initNavBarSwitchContent;
- (void)updateSwitchIndicator;
- (void)onClickNavSwitchButton:(id)arg1;
- (void)onNavigationCancelItemClick:(id)arg1;
- (void)onNavigationBackItemClick:(id)arg1;
- (void)updateNavBarShadow;
- (void)layoutNavContent;
- (void)setNavCancelButtonHidden:(_Bool)arg1;
- (void)setFakeNavBarHidden:(_Bool)arg1 slideAnimated:(_Bool)arg2;
- (void)resetNavSearch;
- (void)updateSwitchButtonSize;
- (void)initNavigationBar;
- (void)onClickKeyboardCancelButton:(id)arg1;
- (void)initKeyboardBanner;
- (void)initView;
- (void)initWebSearchController;
- (id)init;
- (void)keyboardWillShow:(id)arg1;
- (void)keyboardWillHide:(id)arg1;
- (void)viewDidLayoutSubviews;
- (void)viewDidLoad;
- (_Bool)useBlackStatusbar;
- (_Bool)useTransparentNavibar;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

