//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "IMsgExt-Protocol.h"

@class WSRedPointCtrlInfo;

@interface WebSearchRedotMgr : NSObject <IMsgExt>
{
    WSRedPointCtrlInfo *_ctrlInfo;
}

- (void).cxx_destruct;
- (void)parseRedPointCtrlMsg:(id)arg1;
- (void)OnGetNewXmlMsg:(id)arg1 Type:(id)arg2 MsgWrap:(id)arg3;
- (void)clearFFBrowseRedot;
- (void)clearFFSearchRedot;
- (_Bool)shouldShowFFBrowseRedot;
- (_Bool)shouldShowFFSearchRedot;
- (_Bool)shouldShowFindFriendTabRedot;
- (_Bool)isCtrlInfoValid;
- (void)loadData;
- (void)onServiceReloadData;
- (void)dealloc;
- (id)init;

@end

