//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMObject.h"

@class WCDataBase, WCDataBaseTable;

@interface WePkgConfigMgr : MMObject
{
    WCDataBase *_db;
    WCDataBaseTable *_tablePkgRegularConfig;
    WCDataBaseTable *_tablePkgUpdateConfig;
    WCDataBaseTable *_tablePkgGlobalConfig;
}

@property(retain) WCDataBaseTable *tablePkgGlobalConfig; // @synthesize tablePkgGlobalConfig=_tablePkgGlobalConfig;
@property(retain) WCDataBaseTable *tablePkgUpdateConfig; // @synthesize tablePkgUpdateConfig=_tablePkgUpdateConfig;
@property(retain) WCDataBaseTable *tablePkgRegularConfig; // @synthesize tablePkgRegularConfig=_tablePkgRegularConfig;
@property(retain) WCDataBase *db; // @synthesize db=_db;
- (void).cxx_destruct;
- (void)reportDBFail:(id)arg1 Version:(id)arg2 Reason:(id)arg3;
- (id)getRegularConfigListByAppid:(id)arg1;
- (_Bool)haveUpdateConfigFor:(id)arg1;
- (id)getUpdateConfigWhereDownloadNetworkType:(id)arg1;
- (_Bool)deleteUpdateConfigByPkgId:(id)arg1;
- (id)getUpdateConfigByPkgId:(id)arg1;
- (_Bool)insertOrUpdateUpdateConfig:(id)arg1;
- (_Bool)updateDownloadFailCount:(id)arg1 DownloadFailCount:(unsigned int)arg2;
- (id)getAllRegularConfigs;
- (_Bool)deleteRegularConfigByPkgId:(id)arg1;
- (id)getRegularConfigByPkgId:(id)arg1;
- (_Bool)insertOrUpdateRegularConfig:(id)arg1;
- (_Bool)updateLastCheckUpdateTimestamp:(id)arg1;
- (_Bool)getLastCheckUpdateTimestamp:(id)arg1 Timestamp:(unsigned int *)arg2;
- (id)setupTableWithName:(id)arg1 tableClass:(Class)arg2;
- (void)closeDB;
- (void)openDB;

@end

