//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMObject.h"

@class NSObject;
@protocol OS_dispatch_queue;

@interface WePkgOperateUpdateMgr : MMObject
{
    NSObject<OS_dispatch_queue> *_dispatchQueue;
}

@property(readonly, nonatomic) NSObject<OS_dispatch_queue> *dispatchQueue; // @synthesize dispatchQueue=_dispatchQueue;
- (void).cxx_destruct;
- (void)performBlockAndWait:(CDUnknownBlockType)arg1;
- (void)operateUpdateForPkgId:(id)arg1 completeBlock:(CDUnknownBlockType)arg2;
- (id)init;

@end

