//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMObject.h"

#import "WePkgDownloaderDelegate-Protocol.h"

@class NSMutableArray, NSString, WePkgDownloader, WePkgUpdateConfig;

@interface WePkgDownloadMgr : MMObject <WePkgDownloaderDelegate>
{
    NSMutableArray *_arrWaitingUpdateConfigs;
    WePkgUpdateConfig *_downloadingUpdateConfig;
    WePkgDownloader *_downloader;
}

- (void).cxx_destruct;
- (void)downloaderDidFinishDownloadFor:(id)arg1 isSuccess:(_Bool)arg2;
- (_Bool)isNetWorkOkFor:(id)arg1;
- (void)filterInvalidConfigs;
- (void)tryNextDownload;
- (void)clearCurrentDownloadingTask;
- (id)getDownloadingUrlForPkgId:(id)arg1;
- (void)cancelDownloadForPkgId:(id)arg1;
- (_Bool)downloadUpdateForPkgId:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

