//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMObject.h"

#import "WCDBCoding-Protocol.h"

@class NSString, WePkgRegularConfigExt;

@interface WePkgRegularConfigTable : MMObject <WCDBCoding>
{
    unsigned int pkgType;
    NSString *pkgId;
    NSString *appId;
    NSString *entranceDomain;
    WePkgRegularConfigExt *ext;
    long long m___rowID;
}

+ (const basic_string_a490aa4c *)getWCDBPrimaryColumnName;
+ (const struct WCDBIndexHelper *)getWCDBIndexArray;
+ (unsigned long long)getWCDBIndexArrayCount;
+ (const map_490096f0 *)getFileValueTagIndexMap;
+ (id)getFileValueTypeTable;
+ (const map_490096f0 *)getPackedValueTagIndexMap;
+ (id)getPackedValueTypeTable;
+ (const map_64c9abee *)getValueNameIndexMap;
+ (id)getValueTable;
+ (id)dummyObject;
@property(nonatomic) long long __rowID; // @synthesize __rowID=m___rowID;
@property(retain, nonatomic) WePkgRegularConfigExt *ext; // @synthesize ext;
@property(retain, nonatomic) NSString *entranceDomain; // @synthesize entranceDomain;
@property(nonatomic) unsigned int pkgType; // @synthesize pkgType;
@property(retain, nonatomic) NSString *appId; // @synthesize appId;
@property(retain, nonatomic) NSString *pkgId; // @synthesize pkgId;
- (void).cxx_destruct;
- (const map_490096f0 *)getValueTagIndexMap;
- (id)getValueTypeTable;
- (const WCDBCondition_851e0786 *)db_ext;
- (const WCDBCondition_22fabacd *)db_entranceDomain;
- (const WCDBCondition_c6db074e *)db_pkgType;
- (const WCDBCondition_22fabacd *)db_appId;
- (const WCDBCondition_22fabacd *)db_pkgId;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

