//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMService.h"

#import "IWePkgCheckUpdateMgrExt-Protocol.h"
#import "IWePkgDownloadMgrExt-Protocol.h"
#import "IWePkgWebViewNavigationExt-Protocol.h"
#import "MMService-Protocol.h"

@class MMLockMutableDictionary, NSRecursiveLock, NSString, WePkgCheckUpdateMgr, WePkgCleanMgr, WePkgConfigMgr, WePkgDownloadMgr, WePkgOperateUpdateMgr;

@interface WePkgFacade : MMService <MMService, IWePkgCheckUpdateMgrExt, IWePkgDownloadMgrExt, IWePkgWebViewNavigationExt>
{
    NSRecursiveLock *_createPackageLock;
    WePkgConfigMgr *_configMgr;
    WePkgCheckUpdateMgr *_checkMgr;
    WePkgDownloadMgr *_downloadMgr;
    WePkgOperateUpdateMgr *_operateMgr;
    WePkgCleanMgr *_cleanMgr;
    MMLockMutableDictionary *_dicPkgId2Package;
}

@property(retain, nonatomic) MMLockMutableDictionary *dicPkgId2Package; // @synthesize dicPkgId2Package=_dicPkgId2Package;
@property(retain, nonatomic) WePkgCleanMgr *cleanMgr; // @synthesize cleanMgr=_cleanMgr;
@property(retain, nonatomic) WePkgOperateUpdateMgr *operateMgr; // @synthesize operateMgr=_operateMgr;
@property(retain, nonatomic) WePkgDownloadMgr *downloadMgr; // @synthesize downloadMgr=_downloadMgr;
@property(retain, nonatomic) WePkgCheckUpdateMgr *checkMgr; // @synthesize checkMgr=_checkMgr;
@property(retain, nonatomic) WePkgConfigMgr *configMgr; // @synthesize configMgr=_configMgr;
- (void).cxx_destruct;
- (void)reportCheckupdateToDownloadSuccessCostTime:(id)arg1;
- (id)getLocalWePkgInfo:(id)arg1;
- (_Bool)wePkgGlobalConfigDisabled;
- (void)downloadMgr:(id)arg1 didFailForPkgId:(id)arg2 errCode:(int)arg3 NoAutoRetry:(_Bool)arg4;
- (void)downloadMgr:(id)arg1 didSuccessForPkgId:(id)arg2;
- (void)checkUpdateMgr:(id)arg1 didFailForPkgId:(id)arg2 errCode:(int)arg3;
- (void)checkUpdateMgr:(id)arg1 didSuccessForPkgId:(id)arg2 updateConfig:(id)arg3;
- (void)webViewDidExit:(id)arg1;
- (_Bool)checkUpdateFrequenceIsOK:(id)arg1 CheckInterval:(unsigned int)arg2;
- (void)checkUpdate:(id)arg1 CheckInterval:(unsigned int)arg2;
- (_Bool)isWePkgLoadForUrl:(id)arg1 fromEntry:(_Bool)arg2 PkgId:(id *)arg3 Version:(id *)arg4;
- (void)tryToLoadPkgForUrl:(id)arg1 fromEntry:(_Bool)arg2 isSuccess:(_Bool *)arg3;
- (_Bool)updateWePkgUsingWebview:(id)arg1 WebView:(id)arg2;
- (void)setLastDownloadUpdateInDBTime:(unsigned int)arg1;
- (unsigned int)getLastDownloadUpdateInDBTime;
- (void)downloadUpdateInDB;
- (void)tryOperateUpdateForPkgId:(id)arg1;
- (_Bool)isSatisfyNetworkCondition:(id)arg1;
- (id)loadPackage:(id)arg1 createIfNeed:(_Bool)arg2;
- (void)observerMemoryWarning;
- (void)observerWebViewNotification;
- (void)setupMgr;
- (id)getCacheDataForResouceUrlInternal:(id)arg1 mainDocUrl:(id)arg2 PkgId:(id *)arg3 Version:(id *)arg4;
- (id)getCacheDataForResouceUrl:(id)arg1 mainDocUrl:(id)arg2;
- (void)onServiceEnterBackground;
- (void)onServiceEnterForeground;
- (void)onServiceInit;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

