//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMObject.h"

@class NSString;

@interface WePkgRegularConfig : MMObject
{
    unsigned int _uiPkgType;
    unsigned int _uiLastUnusedSeconds;
    unsigned int _uiCheckIntervalSeconds;
    unsigned int _uiLastCheckTimestamp;
    unsigned int _uiLastUsedTimestamp;
    unsigned int _uiDownloadNetworkType;
    unsigned int _uiPkgSizeInBytes;
    NSString *_nsPkgId;
    NSString *_nsAppId;
    NSString *_nsEnteranceDomain;
    NSString *_nsCurrentEnabledVersion;
    NSString *_nsCurrentPkgMd5;
    NSString *_nsCheckResponseMd5;
    NSString *_nsDownloadUrl;
}

+ (id)regularConfigFromTableItem:(id)arg1;
@property(nonatomic) unsigned int uiPkgSizeInBytes; // @synthesize uiPkgSizeInBytes=_uiPkgSizeInBytes;
@property(nonatomic) unsigned int uiDownloadNetworkType; // @synthesize uiDownloadNetworkType=_uiDownloadNetworkType;
@property(retain, nonatomic) NSString *nsDownloadUrl; // @synthesize nsDownloadUrl=_nsDownloadUrl;
@property(retain, nonatomic) NSString *nsCheckResponseMd5; // @synthesize nsCheckResponseMd5=_nsCheckResponseMd5;
@property(nonatomic) unsigned int uiLastUsedTimestamp; // @synthesize uiLastUsedTimestamp=_uiLastUsedTimestamp;
@property(nonatomic) unsigned int uiLastCheckTimestamp; // @synthesize uiLastCheckTimestamp=_uiLastCheckTimestamp;
@property(nonatomic) unsigned int uiCheckIntervalSeconds; // @synthesize uiCheckIntervalSeconds=_uiCheckIntervalSeconds;
@property(nonatomic) unsigned int uiLastUnusedSeconds; // @synthesize uiLastUnusedSeconds=_uiLastUnusedSeconds;
@property(retain, nonatomic) NSString *nsCurrentPkgMd5; // @synthesize nsCurrentPkgMd5=_nsCurrentPkgMd5;
@property(retain, nonatomic) NSString *nsCurrentEnabledVersion; // @synthesize nsCurrentEnabledVersion=_nsCurrentEnabledVersion;
@property(retain, nonatomic) NSString *nsEnteranceDomain; // @synthesize nsEnteranceDomain=_nsEnteranceDomain;
@property(nonatomic) unsigned int uiPkgType; // @synthesize uiPkgType=_uiPkgType;
@property(retain, nonatomic) NSString *nsAppId; // @synthesize nsAppId=_nsAppId;
@property(retain, nonatomic) NSString *nsPkgId; // @synthesize nsPkgId=_nsPkgId;
- (void).cxx_destruct;
- (id)debugDescription;
- (id)generateTableItem;

@end

