//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMObject.h"

@class NSURLSessionDownloadTask, WePkgUpdateConfig;
@protocol WePkgDownloaderDelegate;

@interface WePkgDownloader : MMObject
{
    WePkgUpdateConfig *_oUpdateConfig;
    id <WePkgDownloaderDelegate> _delegate;
    NSURLSessionDownloadTask *_downloadTask;
}

@property(retain, nonatomic) NSURLSessionDownloadTask *downloadTask; // @synthesize downloadTask=_downloadTask;
@property(nonatomic) __weak id <WePkgDownloaderDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) WePkgUpdateConfig *oUpdateConfig; // @synthesize oUpdateConfig=_oUpdateConfig;
- (void).cxx_destruct;
- (id)getTargetPkgFilePath;
- (void)cancelDownload;
- (void)startDownload;
- (id)initWithPkgUpdateConig:(id)arg1 delegate:(id)arg2;

@end

