//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMObject.h"

#import "PBCoding-Protocol.h"

@class NSString;

@interface WePkgUpdateConfigExt : MMObject <PBCoding>
{
    _Bool isReadyForOperation;
    _Bool isClearAllPkgExceptCurrentEnabledVersion;
    unsigned int lastUnusedSeconds;
    unsigned int checkIntervalSeconds;
    unsigned int pkgSizeInBytes;
    NSString *currentEnabledVersion;
    NSString *currentPkgMd5;
    NSString *downloadUrl;
    NSString *checkResponseMd5;
}

+ (void)initialize;
@property(retain, nonatomic) NSString *checkResponseMd5; // @synthesize checkResponseMd5;
@property(nonatomic) _Bool isClearAllPkgExceptCurrentEnabledVersion; // @synthesize isClearAllPkgExceptCurrentEnabledVersion;
@property(nonatomic) _Bool isReadyForOperation; // @synthesize isReadyForOperation;
@property(nonatomic) unsigned int pkgSizeInBytes; // @synthesize pkgSizeInBytes;
@property(retain, nonatomic) NSString *downloadUrl; // @synthesize downloadUrl;
@property(nonatomic) unsigned int checkIntervalSeconds; // @synthesize checkIntervalSeconds;
@property(nonatomic) unsigned int lastUnusedSeconds; // @synthesize lastUnusedSeconds;
@property(retain, nonatomic) NSString *currentPkgMd5; // @synthesize currentPkgMd5;
@property(retain, nonatomic) NSString *currentEnabledVersion; // @synthesize currentEnabledVersion;
- (void).cxx_destruct;
- (const map_490096f0 *)getValueTagIndexMap;
- (id)getValueTypeTable;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

