//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMObject.h"

#import "PBCoding-Protocol.h"

@class NSString;

@interface WePkgRegularConfigExt : MMObject <PBCoding>
{
    unsigned int lastUnusedSeconds;
    unsigned int checkIntervalSeconds;
    unsigned int lastCheckTimestamp;
    unsigned int lastUsedTimestamp;
    unsigned int downloadNetworkType;
    unsigned int pkgSizeInBytes;
    NSString *currentEnabledVersion;
    NSString *currentPkgMd5;
    NSString *checkResponseMd5;
    NSString *downloadUrl;
}

+ (void)initialize;
@property(nonatomic) unsigned int pkgSizeInBytes; // @synthesize pkgSizeInBytes;
@property(nonatomic) unsigned int downloadNetworkType; // @synthesize downloadNetworkType;
@property(retain, nonatomic) NSString *downloadUrl; // @synthesize downloadUrl;
@property(retain, nonatomic) NSString *checkResponseMd5; // @synthesize checkResponseMd5;
@property(nonatomic) unsigned int lastUsedTimestamp; // @synthesize lastUsedTimestamp;
@property(nonatomic) unsigned int lastCheckTimestamp; // @synthesize lastCheckTimestamp;
@property(nonatomic) unsigned int checkIntervalSeconds; // @synthesize checkIntervalSeconds;
@property(nonatomic) unsigned int lastUnusedSeconds; // @synthesize lastUnusedSeconds;
@property(retain, nonatomic) NSString *currentPkgMd5; // @synthesize currentPkgMd5;
@property(retain, nonatomic) NSString *currentEnabledVersion; // @synthesize currentEnabledVersion;
- (void).cxx_destruct;
- (const map_490096f0 *)getValueTagIndexMap;
- (id)getValueTypeTable;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

