//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMUIViewController.h"

#import "FavForwardLogicDelegate-Protocol.h"
#import "FavTagViewDelegate-Protocol.h"
#import "UIAlertViewDelegate-Protocol.h"
#import "WCActionSheetDelegate-Protocol.h"
#import "WNArticleControllerDelegate-Protocol.h"
#import "WNSelectAllViewDelegate-Protocol.h"

@class CMessageWrap, FavForwardLogicController, FavoritesItem, MMTableView, MMTimer, NSString, WNArticleDataController, WNArticleToolView, WNSelectAllView;
@protocol FavNotePostDelegate;

@interface WNArticleViewController : MMUIViewController <WCActionSheetDelegate, FavForwardLogicDelegate, FavTagViewDelegate, UIAlertViewDelegate, WNSelectAllViewDelegate, WNArticleControllerDelegate>
{
    WNArticleToolView *m_toolView;
    WNArticleDataController *m_dataController;
    FavForwardLogicController *_favForwardLogicController;
    MMTableView *m_tableView;
    MMTimer *_saveTimer;
    _Bool bWillDismissAfterRecordEnd;
    _Bool bWillForwardAfterRecordEnd;
    WNSelectAllView *_selectAllView;
    _Bool bDeletePopView;
    _Bool bEditable;
    FavoritesItem *favItem;
    CMessageWrap *recordMsg;
    id <FavNotePostDelegate> favNotePostDelegate;
}

@property(nonatomic) __weak id <FavNotePostDelegate> favNotePostDelegate; // @synthesize favNotePostDelegate;
@property(nonatomic) _Bool bEditable; // @synthesize bEditable;
@property(retain, nonatomic) CMessageWrap *recordMsg; // @synthesize recordMsg;
@property(retain, nonatomic) FavoritesItem *favItem; // @synthesize favItem;
- (void).cxx_destruct;
- (void)keyboardWillHide:(id)arg1;
- (void)keyboardWillShow:(id)arg1;
- (void)keyboardDidHide:(id)arg1;
- (struct CGRect)CGRectConvertWindowRectToCurOri:(struct CGRect)arg1;
- (void)viewDidTransitionToNewSize;
- (void)onSelectAllActionPaste;
- (void)onSelectAllActionCut;
- (void)onSelectAllActionCopy;
- (void)onSelectAllActionDelete;
- (void)onHideSelectAllView;
- (void)hideLoadingView;
- (void)showLoadingView;
- (void)onTxtInfoTextLengthExceed;
- (void)onNoneTxtInfoNumExceed;
- (void)onStopRecordVoice:(id)arg1;
- (void)onSelectAllViewToShow;
- (void)onSelectParaTextForEditing:(struct _NSRange)arg1;
- (id)getViewController;
- (void)reloadAll;
- (void)scrollToIndex:(long long)arg1;
- (void)deleteRowAtIndex:(long long)arg1;
- (void)insertNewRowAtIndex:(long long)arg1 withCount:(long long)arg2;
- (void)insertNewRowAtIndex:(long long)arg1;
- (void)reloadRowAtIndex:(long long)arg1;
- (void)onFavTagEditOK;
- (void)onFavTagEditBegin:(int)arg1;
- (id)getFavForawrdViewController;
- (void)actionSheet:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)onTimeSave;
- (void)stopAutoSaveTimer;
- (void)startAutoSaveTimer;
- (void)onMenuAction:(id)arg1;
- (void)forwardNote;
- (void)saveNote;
- (void)backupNote;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)disMissSelf;
- (void)configNavbar;
- (void)initTableView;
- (void)initToolView;
- (void)initUI;
- (void)initData;
- (_Bool)shouldInteractivePop;
- (_Bool)useTransparentNavibar;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)viewWillBePoped:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

