//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMObject.h"

#import "FavForwardLogicDelegate-Protocol.h"
#import "IFavoritesExt-Protocol.h"
#import "IRecordDownloadExt-Protocol.h"
#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"
#import "WNArticleToolViewDelegate-Protocol.h"
#import "WNParaCellViewDelegate-Protocol.h"

@class CMessageWrap, FavForwardLogicController, FavoritesItem, NSMutableArray, NSString, WNAudioMgr, WNParagraphCellView, WNParagraphMgr;
@protocol WNArticleControllerDelegate;

@interface WNArticleDataController : MMObject <FavForwardLogicDelegate, UITableViewDataSource, UITableViewDelegate, WNParaCellViewDelegate, WNArticleToolViewDelegate, IFavoritesExt, IRecordDownloadExt>
{
    unsigned int _editTime;
    FavoritesItem *m_favItem;
    CMessageWrap *m_recordMsg;
    long long nowEditingIndex;
    WNParagraphCellView *m_EditingCellView;
    WNParagraphMgr *m_wnParaMgr;
    WNAudioMgr *m_audioMgr;
    unsigned int maxObjectId;
    NSMutableArray *m_allParaInfoArray;
    int curUIStatus;
    FavForwardLogicController *m_favForwardLogicController;
    _Bool bEditable;
    _Bool bEdited;
    int WeNoteStatus;
    id <WNArticleControllerDelegate> m_delegate;
    NSMutableArray *m_paraArray;
}

@property(nonatomic) int WeNoteStatus; // @synthesize WeNoteStatus;
@property(nonatomic) _Bool bEdited; // @synthesize bEdited;
@property(nonatomic) _Bool bEditable; // @synthesize bEditable;
@property(retain, nonatomic) NSMutableArray *m_paraArray; // @synthesize m_paraArray;
@property(nonatomic) __weak id <WNArticleControllerDelegate> m_delegate; // @synthesize m_delegate;
- (void).cxx_destruct;
- (void)OnDownloadRecordMessageOK:(id)arg1 DataId:(id)arg2 bThumb:(_Bool)arg3;
- (void)OnUpdateItems:(id)arg1;
- (void)OnDownloadFavoritesItemFail:(id)arg1 LocalDataId:(id)arg2;
- (void)OnDownloadFavoritesItemOK:(id)arg1 LocalDataId:(id)arg2;
- (void)scrollViewDidEndScroll:(id)arg1;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(_Bool)arg2;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (_Bool)ifHasReachedSizeLimit;
- (void)onToolViewStopVoiceRecording:(id)arg1;
- (void)onToolViewStartVoiceRecording:(id)arg1;
- (void)onTextSetBold;
- (void)insertItems:(id)arg1;
- (id)getFavForawrdViewController;
- (_Bool)ifTextLengthExceedLimit:(long long)arg1;
- (void)onStopRecordVoice:(id)arg1;
- (id)getPlayingObjectId;
- (void)onCheckPlayVoice:(id)arg1;
- (void)onTextViewPaste;
- (void)onSelectAll;
- (void)onSelectionChanged:(struct _NSRange)arg1;
- (void)onSendLocationToFriend:(id)arg1 ViewController:(id)arg2;
- (void)onCellViewResighFirstResponser;
- (_Bool)canEdit;
- (_Bool)isEditing;
- (id)getDataArray;
- (id)getFavItem;
- (id)getViewController;
- (void)OnObjectCellDelTextRight:(id)arg1 inCellView:(id)arg2;
- (void)OnObjectCellAddTextRight:(id)arg1 inCellView:(id)arg2 newText:(id)arg3;
- (void)OnObjectCellDelTextLeft:(id)arg1 inCellView:(id)arg2;
- (void)OnObjectCellAddTextLeft:(id)arg1 inCellView:(id)arg2 newText:(id)arg3;
- (void)onMainTextKeyboardBack:(id)arg1 inCellView:(id)arg2;
- (void)setPreviousSelectedToDelete;
- (void)onTextTooLongNeedCut:(id)arg1 inRange:(struct _NSRange)arg2 withText:(id)arg3;
- (void)onTextChanged:(id)arg1 newText:(id)arg2;
- (void)updateEditingCellInfo:(id)arg1;
- (void)textCellShouldEndEditing:(id)arg1;
- (void)textCellDidBeginEditing:(id)arg1;
- (void)textCellShouldBeginEditing:(id)arg1;
- (void)selectAllPaste;
- (void)selectAllCut;
- (void)selectAllCopy;
- (void)getNextPage:(int)arg1;
- (void)geWNNotetNextPage;
- (void)getWNNoteFirstPage;
- (_Bool)isEmpty;
- (void)configParaInfoObjectId:(id)arg1;
- (void)replaceItemAtIndex:(unsigned long long)arg1 withObject:(id)arg2;
- (void)removeItemAtIndex:(unsigned long long)arg1;
- (void)insertItem:(id)arg1 AtIndex:(unsigned long long)arg2;
- (void)initArrayData;
- (int)getIndexOf:(id)arg1;
- (id)getParaInfo:(long long)arg1;
- (_Bool)ifNonTextParaInfoNumExceedLimit:(long long)arg1;
- (_Bool)ifCanInsertItems:(id)arg1;
- (int)getTextLength:(id)arg1;
- (void)selectAllDelete;
- (void)updateSelectAllView:(_Bool)arg1;
- (void)stopPlayAudio;
- (_Bool)isPlayingAudio;
- (void)stopRecord;
- (_Bool)isRecording;
- (void)notifyEdited;
- (_Bool)saveWNArticle;
- (_Bool)backupArticle;
- (void)resetEditingKeyboard;
- (void)hideKeyboard;
- (void)realScrollToEditingCell;
- (void)scrollToEditingCell;
- (void)setEditingCellView:(id)arg1;
- (id)getEditingCellView;
- (_Bool)hasEditingCellView;
- (_Bool)hasHtmlChanged;
- (int)getCurrentHtmlIdIndex;
- (void)configFavItem:(id)arg1;
- (void)configMsg:(id)arg1;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

