//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class MMUIViewController, WNParagraphInfo;

@protocol WNArticleControllerDelegate <NSObject>

@optional
- (void)hideLoadingView;
- (void)showLoadingView;
- (void)onTxtInfoTextLengthExceed;
- (void)onNoneTxtInfoNumExceed;
- (void)onStopRecordVoice:(WNParagraphInfo *)arg1;
- (void)onSelectAllViewToShow;
- (void)onSelectParaTextForEditing:(struct _NSRange)arg1;
- (MMUIViewController *)getViewController;
- (void)reloadAll;
- (void)scrollToIndex:(long long)arg1;
- (void)reloadRowAtIndex:(long long)arg1;
- (void)deleteRowAtIndex:(long long)arg1;
- (void)insertNewRowAtIndex:(long long)arg1 withCount:(long long)arg2;
- (void)insertNewRowAtIndex:(long long)arg1;
- (void)refreshTableViewCellOnIndex:(long long)arg1;
@end

