//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class CMessageWrap, FavoritesItemDataField, NSAttributedString, NSString, WNImageInfo, WNLocationInfo, WNVideoInfo, WNVoiceInfo;

@interface WNParagraphInfo : NSObject
{
    _Bool bTextBeforeObject;
    _Bool bLastTextParagraph;
    _Bool bRemoveSelected;
    _Bool bAllSelected;
    unsigned int type;
    unsigned int textStyle;
    unsigned int editingType;
    NSString *text;
    NSAttributedString *attrText;
    NSString *objectId;
    NSString *objectName;
    FavoritesItemDataField *favData;
    WNLocationInfo *locationInfo;
    WNImageInfo *imageInfo;
    WNVoiceInfo *voiceInfo;
    WNVideoInfo *videoInfo;
    CMessageWrap *originMsgWrap;
}

+ (id)newEmptyTxtInfo;
+ (id)newTextInfoWithAttrString:(id)arg1;
@property(retain, nonatomic) CMessageWrap *originMsgWrap; // @synthesize originMsgWrap;
@property(nonatomic) _Bool bAllSelected; // @synthesize bAllSelected;
@property(nonatomic) _Bool bRemoveSelected; // @synthesize bRemoveSelected;
@property(nonatomic) _Bool bLastTextParagraph; // @synthesize bLastTextParagraph;
@property(nonatomic) _Bool bTextBeforeObject; // @synthesize bTextBeforeObject;
@property(nonatomic) unsigned int editingType; // @synthesize editingType;
@property(retain, nonatomic) WNVideoInfo *videoInfo; // @synthesize videoInfo;
@property(retain, nonatomic) WNVoiceInfo *voiceInfo; // @synthesize voiceInfo;
@property(retain, nonatomic) WNImageInfo *imageInfo; // @synthesize imageInfo;
@property(retain, nonatomic) WNLocationInfo *locationInfo; // @synthesize locationInfo;
@property(retain, nonatomic) FavoritesItemDataField *favData; // @synthesize favData;
@property(retain, nonatomic) NSString *objectName; // @synthesize objectName;
@property(retain, nonatomic) NSString *objectId; // @synthesize objectId;
@property(retain, nonatomic) NSAttributedString *attrText; // @synthesize attrText;
@property(nonatomic) unsigned int textStyle; // @synthesize textStyle;
@property(retain, nonatomic) NSString *text; // @synthesize text;
@property(nonatomic) unsigned int type; // @synthesize type;
- (void).cxx_destruct;
- (id)getThumbPath;
- (id)getDataPath;
- (id)description;
- (_Bool)isTxtParagraph;
- (_Bool)isEmptyParagraph;
- (id)copyWithZone:(struct _NSZone *)arg1;

@end

