//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface WNParaPasteMgr : NSObject
{
}

+ (id)getDescOfParaInfo:(id)arg1;
+ (void)tryClearPasteArray:(int)arg1;
+ (_Bool)hasPasteArrayData;
+ (void)clearPasteData;
+ (_Bool)needClear;
+ (id)getPasteArray;
+ (void)copy:(id)arg1 itemLocalId:(int)arg2;

@end

