//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "UITextViewDelegate-Protocol.h"
#import "WNParaObjectViewDelegate-Protocol.h"
#import "WNParaTextViewDelegate-Protocol.h"

@class NSString, WNParaObjectBaseView, WNParaTextView, WNParagraphInfo;
@protocol WNParaCellViewDelegate;

@interface WNParagraphCellView : UIView <UITextViewDelegate, WNParaObjectViewDelegate, WNParaTextViewDelegate>
{
    _Bool m_bIsLongPressHandled;
    _Bool m_bIsLongPressCanceled;
    _Bool m_touchEnded;
    WNParaObjectBaseView *_objectView;
    WNParaTextView *_leftTextView;
    WNParaTextView *_rightTextView;
    WNParaTextView *_mainTextView;
    UIView *_selectedToRemoveView;
    UIView *_selectedAllView;
    _Bool bMannalSetStyle;
    double m_textHeight;
    WNParagraphInfo *paraInfo;
    id <WNParaCellViewDelegate> delegate;
}

@property(nonatomic) __weak id <WNParaCellViewDelegate> delegate; // @synthesize delegate;
@property(retain, nonatomic) WNParagraphInfo *paraInfo; // @synthesize paraInfo;
- (void).cxx_destruct;
- (void)onTouchDownInObject;
- (void)onTouchDownInRightText;
- (void)onTouchDownInLeftText;
- (void)onTouchEnd;
- (void)onTouchBegin;
- (void)LongPressEvents;
- (void)touchesCancelled:(id)arg1 withEvent:(id)arg2;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (_Bool)isTouchInView:(id)arg1;
- (_Bool)isTouchInRightTextView:(id)arg1;
- (_Bool)isTouchInLeftTextView:(id)arg1;
- (_Bool)isTouchInObjectView:(id)arg1;
- (void)onTextViewMenuPaste;
- (void)onSelectAll;
- (void)onSelectText:(struct _NSRange)arg1;
- (void)textViewDidChangeSelection:(id)arg1;
- (_Bool)textView:(id)arg1 shouldChangeTextInRange:(struct _NSRange)arg2 replacementText:(id)arg3;
- (void)textViewDidChange:(id)arg1;
- (_Bool)textViewShouldEndEditing:(id)arg1;
- (void)textViewHandleLink:(id)arg1;
- (void)textViewDidBeginEditing:(id)arg1;
- (_Bool)textViewShouldBeginEditing:(id)arg1;
- (void)onStopRecordVoice:(id)arg1;
- (id)getPlayingObjectId;
- (void)onCheckPlayVoice:(id)arg1;
- (id)getFavItem;
- (id)getViewController;
- (void)onSendLocationToFriend:(id)arg1 ViewController:(id)arg2;
- (id)getDataArray;
- (void)onObjectHeightChanged;
- (void)updataTableViewHeight;
- (void)onTextViewHeightChange:(double)arg1;
- (void)scrollToCursorForTextView:(id)arg1;
- (void)scrollToVisibleArea;
- (void)setContent:(id)arg1 withSelectRange:(struct _NSRange)arg2;
- (void)setContent:(id)arg1;
- (id)stringAfterCursor;
- (id)stringBeforeCursor;
- (void)hideKeyboard;
- (void)showKeyboard;
- (void)showKeyboardWithSelectionRange:(struct _NSRange)arg1;
- (struct _NSRange)selectedRange;
- (void)updateAllSelectedView;
- (void)updateRemoveSelectedView;
- (void)changeToTextCellWithAttrText:(id)arg1 useLeftTextView:(_Bool)arg2;
- (void)changeToTextCellUsingLeftTextView:(_Bool)arg1;
- (void)changeToOtherObject:(id)arg1;
- (void)changeMainTextViewToRightTextView;
- (void)buildObjectTextView;
- (void)configMainTextView;
- (void)resizeRightTextView;
- (void)buildRightTextView;
- (void)resizeLeftTextView;
- (void)buildLeftTextView;
- (void)buildObjectView;
- (id)getWNTextView:(struct CGRect)arg1;
- (void)layoutView;
- (id)tableView;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

