//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WNParaObjectBaseView.h"

@class UIView;

@interface WNParaObjectFileView : WNParaObjectBaseView
{
    UIView *borderView;
}

- (void).cxx_destruct;
- (void)setUnSelected;
- (void)setSelected;
- (void)onTouchEnd;
- (void)onTouchBegin;
- (void)onClickObject;
- (id)layoutDetailView:(double)arg1;
- (void)layoutView;

@end

