//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMUIViewController.h"

#import "ForwardMessageLogicDelegate-Protocol.h"
#import "FullScreenGestureDelegate-Protocol.h"
#import "IUiUtilExt-Protocol.h"
#import "SightViewDelegate-Protocol.h"
#import "WCActionSheetDelegate-Protocol.h"

@class FavoritesItem, FavoritesItemDataField, ForwardMessageLogicController, MMUIWindow, NSString, SightView, UIImageView, UIView, WXFullScreenGestureRecognizer;

@interface WNSightViewController : MMUIViewController <SightViewDelegate, IUiUtilExt, FullScreenGestureDelegate, ForwardMessageLogicDelegate, WCActionSheetDelegate>
{
    MMUIWindow *_fullScreenWindow;
    UIView *_nodeView;
    UIView *_fullScreenContent;
    SightView *_sightView;
    _Bool _fullScreenPlaying;
    UIImageView *_thumbImageView;
    struct CGRect _thumbRect;
    WXFullScreenGestureRecognizer *m_gestureReconizer;
    _Bool m_bPreventRotate;
    CDStruct_1b6d18a9 m_currentPlayTime;
    ForwardMessageLogicController *m_forwardMsgLogic;
    FavoritesItemDataField *_favData;
    FavoritesItem *_favItem;
    _Bool silencePlay;
}

@property(nonatomic) _Bool silencePlay; // @synthesize silencePlay;
- (void).cxx_destruct;
- (void)tryToSaveVideoToAlbum;
- (void)trySendSightToFriend;
- (void)actionSheet:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)onShowSightAction;
- (void)onMainWindowFrameChanged;
- (void)onFullScreenBackgroupColorAlphaChange:(double)arg1;
- (void)onFullScreenDragToRect:(struct CGRect)arg1;
- (void)onFullScreenLongPressEnd;
- (void)onFullScreenClose;
- (void)onFullScreenDragCancel;
- (void)onFullScreenDragBegin;
- (void)onFullScreenSingleTap;
- (id)getCurrentViewController;
- (void)clearSubviews;
- (double)calTransformFromRect:(struct CGRect)arg1;
- (void)startLoadFullDownloadView;
- (_Bool)checkDownloadForOperateMode:(unsigned int)arg1;
- (void)stopAndCloseFullScreenWindow;
- (void)setThumbImage:(id)arg1;
- (_Bool)isFullScreenPlaying;
- (void)startPlayWithAnimation;
- (void)initGestures;
- (void)initWithWNSight:(id)arg1 FavoritesItem:(id)arg2 superWindow:(id)arg3 thumbView:(id)arg4 nodeView:(id)arg5;
- (_Bool)shouldAutorotate;
- (unsigned long long)supportedInterfaceOrientations;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

