//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface WXGCallstack : NSObject
{
    int _size;
    void **_callstack;
}

@property(readonly, nonatomic) void **callstack; // @synthesize callstack=_callstack;
@property(readonly, nonatomic) int size; // @synthesize size=_size;
- (void)dealloc;
- (id)initWithSize:(int)arg1 callstack:(void *)arg2;

@end

